import { collection, deleteDoc, doc, getDoc, getDocs, limit, orderBy, query, runTransaction, serverTimestamp, setDoc, startAfter } from 'firebase/firestore';
import type { QueryDocumentSnapshot, Timestamp } from 'firebase/firestore';
import { db } from './firebase';
import { brainDay, dailyBrainPuzzles, validBrainAlias, type TimedBrainScore } from './brainMath';
export interface BrainAttempt {day:number;status:'running'|'done';startedAt:Timestamp;finishedAt:Timestamp|null;answers:number[]}
const database=()=>{if(!db)throw new Error('Clasamentul nu este disponibil pe această instanță.');return db;};
export async function loadBrainAttempt(uid:string,day:number){const snap=await getDoc(doc(database(),'brainDays',String(day),'attempts',uid));return snap.exists()?snap.data() as BrainAttempt:null;}
export async function startBrainAttempt(uid:string,day:number){if(day!==brainDay())throw new Error('S-a schimbat ziua. Reîncarcă seria.');const ref=doc(database(),'brainDays',String(day),'attempts',uid);await runTransaction(database(),async tx=>{const existing=await tx.get(ref);if(!existing.exists())tx.set(ref,{day,status:'running',startedAt:serverTimestamp(),finishedAt:null,answers:[]});});const attempt=await loadBrainAttempt(uid,day);if(!attempt)throw new Error('Startul nu a putut fi confirmat.');return attempt;}
export async function finishBrainAttempt(uid:string,day:number,answers:number[],alias:string,publish:boolean){if(day!==brainDay())throw new Error('Ziua s-a încheiat; rezultatul rămâne local.');if(answers.length!==3||answers.some((a,i)=>a!==dailyBrainPuzzles(day)[i].answer))throw new Error('Rezolvă toate cele trei puzzle-uri.');if(publish&&!validBrainAlias(alias))throw new Error('Alege un alias de 2–24 de caractere, fără adresă de email.');const ref=doc(database(),'brainDays',String(day),'attempts',uid);const score=doc(database(),'brainDays',String(day),'scores',uid);await runTransaction(database(),async tx=>{const snap=await tx.get(ref);if(!snap.exists())throw new Error('Începe întâi cronometrul clasamentului.');const attempt=snap.data() as BrainAttempt;if(attempt.status==='done')return;tx.update(ref,{status:'done',finishedAt:serverTimestamp(),answers});if(publish)tx.set(score,{alias:alias.trim(),startedAt:attempt.startedAt,finishedAt:serverTimestamp()});});return (await loadBrainAttempt(uid,day))!;}
export async function publishBrainScore(uid:string,day:number,alias:string){if(!validBrainAlias(alias))throw new Error('Alege un alias de 2–24 de caractere, fără adresă de email.');const attempt=await loadBrainAttempt(uid,day);if(attempt?.status!=='done'||!attempt.finishedAt)throw new Error('Rezolvă mai întâi seria.');await setDoc(doc(database(),'brainDays',String(day),'scores',uid),{alias:alias.trim(),startedAt:attempt.startedAt,finishedAt:attempt.finishedAt});}
export async function withdrawBrainScore(uid:string,day:number){await deleteDoc(doc(database(),'brainDays',String(day),'scores',uid));}
export async function loadBrainScores(day:number,cursor?:QueryDocumentSnapshot){const base=collection(database(),'brainDays',String(day),'scores');const q=cursor?query(base,orderBy('finishedAt','desc'),startAfter(cursor),limit(100)):query(base,orderBy('finishedAt','desc'),limit(100));const result=await getDocs(q);const scores:TimedBrainScore[]=result.docs.map(d=>({id:d.id,alias:d.data().alias,startedMs:(d.data().startedAt as Timestamp).toMillis(),finishedMs:(d.data().finishedAt as Timestamp).toMillis()}));return {scores,cursor:result.docs.at(-1),more:result.size===100};}
export async function loadBrainPublication(uid:string,day:number){const snapshot=await getDoc(doc(database(),'brainDays',String(day),'scores',uid));return snapshot.exists()?snapshot.data().alias as string:null;}
