export const DAY_MS=86400000;
export const brainDay=(now=Date.now())=>Math.floor(now/DAY_MS);
export const brainDate=(day:number)=>new Intl.DateTimeFormat('ro-RO',{dateStyle:'long',timeZone:'UTC'}).format(new Date(day*DAY_MS));
export interface BrainPuzzle {id:string;title:string;prompt:string;answer:number;explanation:string;hint:string;grid?:{rows:number;columns:number};sequence?:number[]}
export function dailyBrainPuzzles(day:number):BrainPuzzle[]{if(!Number.isInteger(day)||day<0)throw new Error('Zi invalidă.');const seed=day%997;const a=2+seed%8;const b=3+Math.floor(seed/8)%9;const c=2+Math.floor(seed/72)%5;const variant=day%3;
 const sequence=variant===0?Array.from({length:3},(_,i)=>(a+i)**2):variant===1?[a,a+b,a+2*b+1,a+3*b+3]:[a,a+b,a+b-c,a+2*b-c];
 const answer=variant===0?(a+3)**2:variant===1?a+4*b+6:a+2*b-2*c;
 const first:BrainPuzzle={id:`brain-${day}-pattern`,title:'Detectivul șirurilor',prompt:`Continuă regula: ${sequence.join(', ')}. Care este următorul număr?`,answer,sequence,hint:variant===0?'Caută pătrate consecutive.':variant===1?'Compară diferențele dintre vecini.':'Pașii se repetă alternativ.',explanation:variant===0?`Numerele sunt pătratele lui ${a}, ${a+1}, ${a+2}. Urmează ${a+3}²=${answer}.`:variant===1?`Diferențele sunt ${b}, ${b+1}, ${b+2}; urmează ${b+3}. ${sequence[3]}+${b+3}=${answer}.`:`Alternăm +${b} și −${c}. Urmează ${sequence[3]}−${c}=${answer}.`};
 const second:BrainPuzzle={id:`brain-${day}-balance`,title:'Balanța logică',prompt:day%2===0?`Două balanțe dau 2x+y=${2*a+b} și x+2y=${a+2*b}. Cât este x·y?`:`Două balanțe dau 3x+y=${3*a+b} și x+y=${a+b}. Cât este x·y?`,answer:a*b,hint:'Elimină o necunoscută comparând cele două egalități.',explanation:day%2===0?`Dublăm prima egalitate și o scădem pe a doua: 3x=${3*a}, deci x=${a}. Apoi y=${b}, iar x·y=${a*b}.`:`Scădem a doua egalitate din prima: 2x=${2*a}, deci x=${a}. Apoi y=${b}, iar x·y=${a*b}.`};
 const stairs=c+3;const ways=[1,1];for(let i=2;i<=stairs;i++)ways[i]=ways[i-1]+ways[i-2];
 const third:BrainPuzzle=day%2===0?{id:`brain-${day}-count`,title:'Câte dreptunghiuri?',prompt:`O grilă are 2 rânduri și ${c} coloane de pătrate. Câte dreptunghiuri diferite poți forma folosind liniile grilei? Include pătratele.`,answer:3*c*(c+1)/2,grid:{rows:2,columns:c},hint:'Alege două linii orizontale și două linii verticale.',explanation:`Există 3 moduri de a alege două dintre cele 3 linii orizontale și ${c*(c+1)/2} moduri pentru cele ${c+1} linii verticale. Total: 3·${c*(c+1)/2}=${3*c*(c+1)/2}.`}:{id:`brain-${day}-count`,title:'Treptele istețe',prompt:`O scară are ${stairs} trepte. Poți urca 1 sau 2 trepte la fiecare pas. Câte moduri diferite există de a ajunge sus?`,answer:ways[stairs],hint:'Ultimul pas vine de la treapta anterioară sau de la cea cu două mai jos.',explanation:`Numărul de moduri satisface F(n)=F(n−1)+F(n−2), cu F(0)=F(1)=1. Pentru ${stairs} trepte: ${ways.slice(0,stairs+1).join(', ')}. Răspuns: ${ways[stairs]}.`};return [first,second,third];}
export function parseBrainAnswer(text:string):number|null {if(!/^\s*-?\d{1,6}\s*$/.test(text))return null;const value=Number(text);return Number.isSafeInteger(value)?value:null;}
export function formatBrainTime(ms:number){const seconds=Math.floor(Math.max(0,ms)/1000);return `${Math.floor(seconds/60)}:${String(seconds%60).padStart(2,'0')}.${Math.floor(Math.max(0,ms)%1000/100)}`;}
export interface TimedBrainScore {id:string;alias:string;startedMs:number;finishedMs:number}
export function rankBrainScores(scores:TimedBrainScore[]){const sorted=scores.filter(s=>Number.isFinite(s.startedMs)&&Number.isFinite(s.finishedMs)&&s.finishedMs>=s.startedMs).map(s=>({...s,elapsedMs:s.finishedMs-s.startedMs})).sort((a,b)=>a.elapsedMs-b.elapsedMs||a.finishedMs-b.finishedMs||a.id.localeCompare(b.id));return sorted.map((s,i)=>({...s,place:i>0&&s.elapsedMs===sorted[i-1].elapsedMs?sorted.findIndex(item=>item.elapsedMs===s.elapsedMs)+1:i+1}));}
export function validBrainAlias(alias:string){return /^[A-Za-zÀ-ÖØ-öø-ɏ0-9 ._-]{2,24}$/.test(alias.trim());}
