import { collection, doc, getDocs, orderBy, query, runTransaction, serverTimestamp, updateDoc, where, limit } from 'firebase/firestore';
import type { Timestamp } from 'firebase/firestore';
import { db } from './firebase';
export type FeedbackKind='feedback'|'feature'|'problem';
export type FeedbackStatus='new'|'planned'|'closed';
export interface FeedbackInput {kind:FeedbackKind;title:string;message:string}
export interface FeedbackItem extends FeedbackInput {id:string;uid:string;status:FeedbackStatus;response:string;createdAt:Timestamp|null}
export function validateFeedback(input:FeedbackInput){if(!['feedback','feature','problem'].includes(input.kind))return 'Alege tipul mesajului.';if(input.title.trim().length<5||input.title.trim().length>100)return 'Titlul trebuie să aibă între 5 și 100 de caractere.';if(input.message.trim().length<20||input.message.trim().length>2000)return 'Mesajul trebuie să aibă între 20 și 2000 de caractere.';return '';}
export async function sendFeedback(uid:string,input:FeedbackInput){const error=validateFeedback(input);if(error)throw new Error(error);if(!db)throw new Error('Trimiterea nu este configurată. Ciorna rămâne salvată.');const database=db;const feedback=doc(collection(database,'feedback'));const cooldown=doc(database,'users',uid,'feedbackLimits','main');await runTransaction(database,async tx=>{const last=await tx.get(cooldown);const time=last.data()?.submittedAt as Timestamp|undefined;if(time&&Date.now()-time.toMillis()<60000)throw new Error('Așteaptă un minut înainte de următorul mesaj.');tx.set(feedback,{uid,kind:input.kind,title:input.title.trim(),message:input.message.trim(),status:'new',response:'',createdAt:serverTimestamp()});tx.set(cooldown,{submittedAt:serverTimestamp(),feedbackId:feedback.id});});return feedback.id;}
export async function loadFeedback(uid?:string):Promise<FeedbackItem[]>{if(!db)return [];const ref=collection(db,'feedback');const q=uid?query(ref,where('uid','==',uid),limit(100)):query(ref,orderBy('createdAt','desc'),limit(100));const result=await getDocs(q);return result.docs.map(d=>({...d.data(),id:d.id} as FeedbackItem)).sort((a,b)=>(b.createdAt?.toMillis()??0)-(a.createdAt?.toMillis()??0));}
export async function triageFeedback(id:string,status:FeedbackStatus,response:string){if(!db)throw new Error('Baza de date nu este configurată.');await updateDoc(doc(db,'feedback',id),{status,response:response.trim().slice(0,1000)});}
export interface EngagementPreferences {reminders:boolean;time:'0800'|'1600'|'1800'|'2000';days:'daily'|'weekdays';releaseSeen:string;reminderSeen:string}
export const defaultPreferences:EngagementPreferences={reminders:false,time:'1800',days:'daily',releaseSeen:'',reminderSeen:''};
export function readPreferences(key:string):EngagementPreferences{try{const raw=JSON.parse(localStorage.getItem(key)??'null');return {reminders:raw?.reminders===true,time:['0800','1600','1800','2000'].includes(raw?.time)?raw.time:'1800',days:raw?.days==='weekdays'?'weekdays':'daily',releaseSeen:typeof raw?.releaseSeen==='string'?raw.releaseSeen:'',reminderSeen:typeof raw?.reminderSeen==='string'?raw.reminderSeen:''};}catch{return {...defaultPreferences};}}
export function reminderDue(p:EngagementPreferences,studied:string[],now=new Date()){const today=`${now.getFullYear()}-${String(now.getMonth()+1).padStart(2,'0')}-${String(now.getDate()).padStart(2,'0')}`;return p.reminders&&p.reminderSeen!==today&&!studied.includes(today)&&(p.days==='daily'||(now.getDay()>0&&now.getDay()<6))&&(now.getHours()*60+now.getMinutes()>=Number(p.time.slice(0,2))*60+Number(p.time.slice(2)));}
export const calendarPath=(p:Pick<EngagementPreferences,'days'|'time'>)=>`/calendar/axioma-${p.days}-${p.time}.ics`;
