import { test,expect } from '@playwright/test';
import AxeBuilder from '@axe-core/playwright';
import { getRecap } from '../../src/content/recaps';
import { productReleases } from '../../src/content/releases';

test('release announcement is unread once per version and visiting notes acknowledges it',async({page})=>{
 await page.addInitScript(()=>{if(!localStorage.getItem('axioma:engagement:guest'))localStorage.setItem('axioma:engagement:guest',JSON.stringify({releaseSeen:'1.2.1'}));});await page.goto('/');const banner=page.getByRole('region',{name:'Versiune nouă'});await expect(banner).toContainText(`v${productReleases[0].version}`);await page.getByRole('button',{name:'Închide anunțul versiunii'}).click();await expect(banner).toHaveCount(0);await page.reload();await expect(banner).toHaveCount(0);await page.getByRole('link',{name:'Ce e nou',exact:true}).click();await expect(page.getByRole('region',{name:'Istoricul lansărilor'}).getByText(`v${productReleases[0].version}`,{exact:true})).toBeVisible();
});
test('feedback guests can draft and reload, but cannot send anonymous submissions',async({page})=>{
 await page.goto('/feedback');await page.getByLabel('Tipul mesajului').selectOption('feature');await page.getByLabel('Titlu',{exact:true}).fill('Mai multă geometrie');await page.getByLabel('Mesaj',{exact:true}).fill('Aș dori exerciții interactive de geometrie în spațiu.');await page.reload();await expect(page.getByLabel('Titlu',{exact:true})).toHaveValue('Mai multă geometrie');await page.getByRole('button',{name:'Trimite mesajul'}).click();await expect(page.getByRole('status')).toContainText('Conectează-te');expect(await page.evaluate(()=>JSON.parse(localStorage.getItem('axioma:feedback-draft:guest')!).kind)).toBe('feature');
});
test('reminders opt in, persist their schedule, offer calendar feeds, dismiss and unsubscribe',async({page})=>{
 await page.clock.install({time:new Date(2026,9,12,19,0)});await page.goto('/remindere');const toggle=page.getByRole('checkbox',{name:'Activează reminderele în Axioma'});await expect(toggle).not.toBeChecked();await toggle.check();await page.getByLabel('Ora locală').selectOption('1600');await page.getByRole('combobox',{name:'Zile',exact:true}).selectOption('weekdays');await page.reload();await expect(toggle).toBeChecked();await expect(page.getByLabel('Ora locală')).toHaveValue('1600');await expect(page.getByRole('link',{name:'Abonează-te în calendar'})).toHaveAttribute('href',/webcal:.*axioma-weekdays-1600.ics/);const response=await page.request.get('/calendar/axioma-weekdays-1600.ics');expect(response.ok()).toBe(true);expect(await response.text()).toContain('RRULE:FREQ=WEEKLY;BYDAY=MO,TU,WE,TH,FR');await page.getByRole('button',{name:'Amintește-mi mâine'}).click();await expect(page.getByRole('region',{name:'Reminder de studiu'})).toHaveCount(0);await page.reload();await expect(page.getByRole('region',{name:'Reminder de studiu'})).toHaveCount(0);await toggle.uncheck();await page.reload();await expect(toggle).not.toBeChecked();
});
test('keyboard practice has a journey and streaks; mistake retries preserve original XP and score',async({page})=>{
 const pack=getRecap('5','2026')!;await page.goto('/quiz/recap/5');for(let i=0;i<pack.questions.length;i++){const q=pack.questions[i];await page.locator('.question-card h2').focus();await page.keyboard.press(String((i===0?(q.answer+1)%4:q.answer)+1));await page.keyboard.press('Enter');await expect(page.locator('.answer-feedback')).toBeVisible();if(i===2)await expect(page.locator('.journey-caption')).toContainText('2 răspunsuri corecte la rând');await page.locator('.question-card h2').focus();await page.keyboard.press('Enter');}
 await expect(page.getByRole('heading',{name:'Ai reușit!'})).toBeVisible();await expect(page.locator('.xp-chip')).toContainText('0 XP');await page.getByRole('button',{name:'Reia cele 1 întrebări de exersat'}).click();const practice=page.getByRole('region',{name:'Reia greșelile'});await practice.getByRole('radio').nth(pack.questions[0].answer).check();await practice.getByRole('button',{name:'Verifică reluarea'}).click();await page.reload();await page.getByRole('button',{name:'Reia cele 1 întrebări de exersat'}).click();await expect(practice.getByRole('status')).toContainText('Exact!');await practice.getByRole('button',{name:'Continuă reluarea'}).click();await expect(practice.getByRole('status')).toContainText('Ai reluat toate');await expect(page.locator('.result-score')).toContainText('11');await expect(page.locator('.xp-chip')).toContainText('0 XP');expect(await page.evaluate(()=>JSON.parse(localStorage.getItem('axioma:guest')!).results)).toEqual({});
});
test('math is rendered in recap prose, worked steps, quiz options and lab captions',async({page})=>{
 await page.goto('/recapitulare/5');await expect(page.locator('.recap-topic-body .rendered-math .katex-mathml').first()).toBeAttached();await expect(page.locator('.recap-example .katex').first()).toBeVisible();await page.goto('/quiz/recap/5');await expect(page.locator('.question-card h2 .katex-mathml').first()).toBeAttached();await expect(page.locator('.answer-option .katex')).toHaveCount(4);await page.getByRole('radio').first().check();await page.getByRole('button',{name:'Verifică răspunsul'}).click();await expect(page.locator('.answer-feedback .katex').first()).toBeVisible();await page.goto('/laborator');await expect(page.locator('.lab-caption .katex-mathml')).toHaveCount(1);await page.getByRole('tab',{name:'Integrala',exact:true}).click();await expect(page.locator('.lab-caption .katex-html .mfrac')).toBeVisible();await expect(page.locator('.katex-error')).toHaveCount(0);
});
test('new engagement pages and math-heavy quizzes fit narrow phones and pass accessibility',async({page})=>{
 await page.emulateMedia({reducedMotion:'reduce'});await page.setViewportSize({width:320,height:568});for(const route of ['/feedback','/remindere','/quiz/recap/5','/recapitulare/7']){await page.goto(route);await expect(page.locator('h1')).toBeVisible();expect(await page.evaluate(()=>document.documentElement.scrollWidth)).toBeLessThanOrEqual(321);const audit=await new AxeBuilder({page}).withTags(['wcag2a','wcag2aa','wcag21aa']).analyze();expect(audit.violations.filter(v=>['serious','critical'].includes(v.impact??''))).toEqual([]);}
});

test('an open app detects a newly deployed release without interrupting a quiz',async({page})=>{
 await page.route('**/release.json',route=>route.fulfill({json:{version:'1.2.3'}}));await page.goto('/quiz/recap/5');await page.getByRole('radio').first().check();await expect(page.getByRole('region',{name:'Actualizare disponibilă'})).toContainText('v1.2.3');await expect(page.getByRole('button',{name:'Reîncarcă pentru versiunea nouă'})).toBeVisible();await page.reload();await expect(page.getByRole('radio').first()).toBeChecked();await expect(page.getByText('Întrebarea 1 din 12')).toBeVisible();
});
