import { test,expect } from '@playwright/test';
import AxeBuilder from '@axe-core/playwright';
import { findLesson } from '../../src/content/curriculum';
test('supplementary practice resumes and completes without XP or mastery changes',async({page})=>{
 const lesson=findLesson('logica')!;await page.goto('/lectie/logica');await page.getByRole('link',{name:'Exerciții suplimentare',exact:true}).click();await expect(page.getByText('Întrebarea 1 din 3')).toBeVisible();
 for(let i=0;i<lesson.practiceQuestions.length;i++){const q=lesson.practiceQuestions[i];await page.getByRole('radio').nth(q.answer).check();await page.getByRole('button',{name:'Verifică răspunsul'}).click();await expect(page.getByRole('status')).toContainText(q.explanation);if(i===0){await page.reload();await expect(page.getByRole('status')).toContainText(q.explanation);}await page.getByRole('button',{name:/Următoarea întrebare|Vezi rezultatul/}).click();}
 await expect(page.getByRole('heading',{name:'Ai reușit!'})).toBeVisible();await expect(page.getByText(/Antrenament fără XP/)).toBeVisible();await expect(page.locator('.xp-chip')).toContainText('0 XP');await page.reload();await expect(page.locator('.review-item')).toHaveCount(3);await page.goto('/lectie/logica');await expect(page.getByText('Stăpânită',{exact:true})).toHaveCount(0);
});
test('term and symbol explanations support hover, focus, tap and dismissal inside viewport',async({page,isMobile})=>{
 await page.emulateMedia({reducedMotion:'reduce'});await page.goto('/lectie/derivate');const term=page.locator('.theory-paragraph').getByRole('button',{name:/Explică/}).first();
 if(isMobile)await term.tap();else await term.hover();await expect(page.getByRole('tooltip')).toBeVisible();
 if(!isMobile){await page.getByRole('tooltip').hover();await page.waitForTimeout(250);await expect(page.getByRole('tooltip')).toBeVisible();}
 const box=await page.getByRole('tooltip').boundingBox();const viewport=page.viewportSize()!;expect(box!.x).toBeGreaterThanOrEqual(0);expect(box!.x+box!.width).toBeLessThanOrEqual(viewport.width);
 await page.keyboard.press('Escape');await expect(page.getByRole('tooltip')).toHaveCount(0);await page.getByRole('heading',{level:1}).click();await term.focus();await expect(page.getByRole('tooltip')).toBeVisible();await page.getByRole('heading',{level:1}).click();await expect(page.getByRole('tooltip')).toHaveCount(0);
 await page.goto('/lectie/integrala');const symbol=page.getByRole('button',{name:'Explică simbolul ∫: Integrală'});await symbol.focus();await expect(page.getByRole('tooltip')).toContainText('integrare');const results=await new AxeBuilder({page}).withTags(['wcag2a','wcag2aa','wcag21aa']).analyze();expect(results.violations.filter(v=>['serious','critical'].includes(v.impact??''))).toEqual([]);await page.keyboard.press('Escape');await expect(page.getByRole('tooltip')).toHaveCount(0);const caption=page.locator('.lab-caption').getByRole('button',{name:'Explică «∫»'});await caption.focus();await expect(page.getByRole('tooltip')).toBeVisible();const captionAudit=await new AxeBuilder({page}).withTags(['wcag2a','wcag2aa','wcag21aa']).analyze();expect(captionAudit.violations.filter(v=>['serious','critical'].includes(v.impact??''))).toEqual([]);
});
test('four new labs explore boundary cases and reset the selected example',async({page})=>{
 await page.goto('/laborator');await expect(page.getByRole('tab')).toHaveCount(9);await page.getByRole('tab',{name:'Numere complexe',exact:true}).click();await expect(page.locator('.lab-caption')).toContainText('|z| = 5.00');const triangle=await page.locator('.lab svg g path').first().getAttribute('d');const [ox,oy,px,py]=triangle!.match(/-?\d+(?:\.\d+)?/g)!.map(Number);expect((oy-py)/(px-ox)).toBeCloseTo(4/3);await page.getByLabel('Exemplu de laborator').selectOption('zero');await expect(page.locator('.lab-caption')).toContainText('nedefinit');await page.getByLabel('Partea reală',{exact:true}).fill('2');await page.getByRole('button',{name:'Resetează graficul'}).click();await expect(page.getByLabel('Partea reală',{exact:true})).toHaveValue('0');
 await page.getByRole('tab',{name:'Exponențiale',exact:true}).click();await page.getByLabel('Exemplu de laborator').selectOption('decay');await expect(page.locator('.lab-caption')).toContainText('0.250');await page.getByLabel('Baza a').fill('1');await expect(page.locator('.lab-caption')).toContainText('1.000');
 await page.getByRole('tab',{name:'Progresii',exact:true}).click();await expect(page.locator('.lab-caption')).toContainText('S5 = 25.00');await page.getByLabel('Exemplu de laborator').selectOption('ratio-one');await expect(page.locator('.lab-caption')).toContainText('S5 = 15.00');
 await page.getByRole('tab',{name:'Probabilitate',exact:true}).click();await expect(page.locator('.lab-caption')).toContainText('0.3750');await page.getByLabel('Exemplu de laborator').selectOption('certain');await expect(page.locator('.lab-caption')).toContainText('1.0000');await page.getByLabel('Probabilitatea p').fill('0');await page.getByLabel('Succese k').fill('0');await expect(page.locator('.lab-caption')).toContainText('1.0000');await page.getByLabel('Număr de încercări').fill('2');await expect(page.getByLabel('Succese k')).toHaveAttribute('max','2');
 await expect.poll(()=>page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1)).toBe(true);
});
test('lab tabs support keyboard navigation and each lab has three examples',async({page})=>{
 await page.goto('/laborator');const first=page.getByRole('tab',{name:'Parabola',exact:true});await first.focus();await page.keyboard.press('End');await expect(page.getByRole('tab',{name:'Probabilitate',exact:true})).toBeFocused();await page.keyboard.press('ArrowRight');await expect(first).toBeFocused();for(const tab of await page.getByRole('tab').all()){await tab.click();await expect(page.getByLabel('Exemplu de laborator').locator('option')).toHaveCount(3);await expect(page.locator('.lab-investigation')).toBeVisible();}
 await page.goto('/quiz/test/9');await expect(page.locator('.explained-term')).toHaveCount(0);await expect(page.getByRole('tooltip')).toHaveCount(0);
});
