import { test,expect } from '@playwright/test';
import AxeBuilder from '@axe-core/playwright';
import { getRecap } from '../../src/content/recaps';
test('class entry offers optional prior-year recap and a direct start in every grade',async({page})=>{
 await page.goto('/');await page.getByRole('link',{name:'Începe să înveți',exact:true}).click();await expect(page.getByRole('heading',{name:'Pregătit pentru clasa a IX-a?'})).toBeVisible();await expect(page.getByRole('link',{name:'Începe recapitularea'})).toHaveAttribute('href','/recapitulare/gimnaziu');await page.getByRole('link',{name:'Începe clasa a IX-a'}).click();await expect(page.getByRole('heading',{name:'Propoziții și raționamente',exact:true})).toBeVisible();
 for(const [grade,previous,label] of [['10','9','X'],['11','10','XI'],['12','11','XII']]){await page.getByLabel('Clasa',{exact:true}).selectOption(grade);await page.goto('/incepe');await expect(page.getByRole('heading',{name:`Pregătit pentru clasa a ${label}-a?`})).toBeVisible();await expect(page.getByRole('link',{name:'Începe recapitularea'})).toHaveAttribute('href',`/recapitulare/${previous}`);await expect(page.getByRole('link',{name:`Începe clasa a ${label}-a`})).toBeVisible();await page.getByRole('link',{name:'Începe recapitularea'}).click();await expect(page.getByLabel('Clasa',{exact:true})).toHaveValue(grade);}
});
test('recap hub provides all grade packs, examples and helpful invalid-route recovery',async({page})=>{
 await page.goto('/recapitulare');await expect(page.locator('.recap-grade-card')).toHaveCount(8);await page.getByRole('link',{name:/Clasa a VII-a/}).click();await expect(page.locator('.recap-topic')).toHaveCount(4);await expect(page.locator('[data-math-text="Rezultatul este 5√2."]')).toBeVisible();await page.locator('.recap-topic').nth(1).locator('summary').click();await expect(page.locator('[data-math-text="Verificăm: 3·5−5=10."]')).toBeVisible();await expect(page.getByRole('link',{name:'Exersează recapitularea',exact:true})).toHaveCount(2);await page.goto('/recapitulare/13');await expect(page.getByRole('heading',{name:'Recapitularea nu a fost găsită.'})).toBeVisible();await page.getByRole('link',{name:'Alege o recapitulare'}).click();await expect(page.getByRole('heading',{name:'Recapitulări.'})).toBeVisible();
});
test('middle-school recap practice resumes, provides worked feedback and preserves mastery and XP',async({page})=>{
 const pack=getRecap('5','2026')!;await page.goto('/quiz/recap/5');
 for(let i=0;i<pack.questions.length;i++){const q=pack.questions[i];await page.getByRole('radio').nth(q.answer).check();await page.getByRole('button',{name:'Verifică răspunsul'}).click();await expect(page.getByRole('status').locator('[data-math-text]')).toHaveAttribute('data-math-text',q.explanation);await page.getByRole('button',{name:/Următoarea întrebare|Vezi rezultatul/}).click();if(i===0){await page.reload();await expect(page.getByText('Întrebarea 2 din 12')).toBeVisible();}}
 await expect(page.getByRole('heading',{name:'Ai reușit!'})).toBeVisible();await expect(page.locator('.xp-chip')).toContainText('0 XP');await expect(page.locator('.review-item')).toHaveCount(12);await page.reload();await expect(page.getByText(/Antrenament fără XP/)).toBeVisible();expect(await page.evaluate(()=>JSON.parse(localStorage.getItem('axioma:guest')!).results)).toEqual({});
});
test('high-school recap respects curriculum changes, keeps current class and persists separate sessions',async({page})=>{
 await page.goto('/recapitulare/10');await page.getByLabel('Clasa',{exact:true}).selectOption('11');await expect(page.getByRole('heading',{name:'Polinoame. Împărțire și Bézout',exact:true})).toBeVisible();await page.getByLabel('Programa',{exact:true}).selectOption('legacy');await expect(page.getByRole('heading',{name:'Polinoame. Împărțire și Bézout',exact:true})).toHaveCount(0);await page.getByRole('link',{name:'Exersează recapitularea',exact:true}).first().click();await page.getByRole('radio').first().check();await page.getByRole('button',{name:'Verifică răspunsul'}).click();await page.getByRole('button',{name:'Următoarea întrebare'}).click();await page.reload();await expect(page.getByText('Întrebarea 2 din 12')).toBeVisible();await page.getByLabel('Programa',{exact:true}).selectOption('2026');await expect(page.getByText('Întrebarea 1 din 12')).toBeVisible();await page.getByLabel('Programa',{exact:true}).selectOption('legacy');await expect(page.getByText('Întrebarea 2 din 12')).toBeVisible();await expect(page.getByLabel('Clasa',{exact:true})).toHaveValue('11');
});
test('lab picker supports pointer, keyboard, Escape, outside dismissal and selected reset',async({page,isMobile})=>{
 await page.emulateMedia({reducedMotion:'reduce'});await page.goto('/laborator');const picker=page.getByRole('combobox',{name:'Exemplu de laborator'});await picker.click();await expect(page.getByRole('listbox')).toBeVisible();await expect(page.getByRole('option',{name:'Un minim sub axă'})).toHaveAttribute('aria-selected','true');const choice=page.getByRole('option',{name:'Un maxim deasupra axei'});if(isMobile)await choice.tap();else await choice.click();await expect(picker).toContainText('Un maxim deasupra axei');await expect(page.getByRole('slider',{name:'Coeficient a',exact:true})).toHaveValue('-1');await expect(page.getByRole('slider',{name:'Coeficient b',exact:true})).toHaveValue('2');
});
test('picker keyboard and open-state accessibility',async({page})=>{
 await page.emulateMedia({reducedMotion:'reduce'});await page.goto('/laborator');const picker=page.getByRole('combobox',{name:'Exemplu de laborator'});await picker.focus();await page.keyboard.press('ArrowDown');await page.keyboard.press('End');await page.keyboard.press('Enter');await expect(picker).toContainText('O rădăcină dublă');await page.getByRole('slider',{name:'Coeficient a',exact:true}).fill('2');await page.getByRole('button',{name:'Resetează graficul'}).click();await expect(page.getByRole('slider',{name:'Coeficient a',exact:true})).toHaveValue('1');await picker.click();const result=await new AxeBuilder({page}).withTags(['wcag2a','wcag2aa','wcag21aa']).analyze();expect(result.violations.filter(v=>['serious','critical'].includes(v.impact??'')).map(v=>({id:v.id,nodes:v.nodes.map(n=>n.target)}))).toEqual([]);await page.keyboard.press('Escape');await expect(page.getByRole('listbox')).toHaveCount(0);await picker.click();await page.getByRole('heading',{level:1}).click();await expect(page.getByRole('listbox')).toHaveCount(0);await picker.focus();await page.keyboard.press(' ');await page.keyboard.press('Tab');await expect(page.getByRole('listbox')).toHaveCount(0);await expect(picker).not.toBeFocused();
});
test('recaps and lab popup fit representative phone, landscape, tablet, desktop and zoom widths',async({page})=>{
 test.setTimeout(120000);
 await page.emulateMedia({reducedMotion:'reduce'});
 for(const [width,height] of [[320,568],[360,640],[393,852],[844,390],[768,1024],[820,1180],[1024,768],[1280,800],[1440,900],[1920,1080],[2560,1440],[640,480]]){
  await page.setViewportSize({width,height});
  for(const route of ['/','/materie','/lectie/gradul-doi','/quiz/recap/5','/provocari','/prieteni','/ranguri','/noutati','/viitor','/cont','/admin','/recapitulare','/recapitulare/gimnaziu','/incepe','/laborator']){await page.goto(route);await expect(page.locator('h1')).toBeVisible();await expect.poll(()=>page.evaluate(w=>document.documentElement.scrollWidth<=w+1,width),{message:`Overflow: ${route} at ${width}×${height}`}).toBe(true);}
  const picker=page.getByRole('combobox',{name:'Exemplu de laborator'});await picker.scrollIntoViewIfNeeded();await picker.click();const bounds=await page.getByRole('listbox').boundingBox();expect(bounds!.x).toBeGreaterThanOrEqual(0);expect(bounds!.y).toBeGreaterThanOrEqual(0);expect(bounds!.x+bounds!.width).toBeLessThanOrEqual(width);expect(bounds!.y+bounds!.height).toBeLessThanOrEqual(height);await page.getByRole('option',{name:'Un maxim deasupra axei'}).click();await expect(picker).toContainText('Un maxim deasupra axei');
 }
});
test('new recap pages meet accessibility checks in reduced motion',async({page})=>{
 await page.emulateMedia({reducedMotion:'reduce'});
 for(const route of ['/incepe','/recapitulare','/recapitulare/5','/recapitulare/9','/quiz/recap/gimnaziu']){await page.goto(route);await expect(page.locator('h1')).toBeVisible();const result=await new AxeBuilder({page}).withTags(['wcag2a','wcag2aa','wcag21aa']).analyze();expect(result.violations.filter(v=>['serious','critical'].includes(v.impact??'')).map(v=>({id:v.id,nodes:v.nodes.map(n=>n.target)})),route).toEqual([]);}
});
