// @vitest-environment jsdom
import { beforeEach,afterEach,it,expect,vi } from 'vitest';
import { render,screen,fireEvent,waitFor,cleanup } from '@testing-library/react';
import { MemoryRouter } from 'react-router-dom';
import { BrainPuzzles } from '../src/pages/BrainPuzzles';
import { brainDay,dailyBrainPuzzles } from '../src/lib/brainMath';
const cloud=vi.hoisted(()=>({load:vi.fn(),publication:vi.fn(),start:vi.fn(),finish:vi.fn(),publish:vi.fn(),withdraw:vi.fn(),scores:vi.fn()}));
vi.mock('../src/hooks/useLearning',()=>({useLearning:()=>({user:{uid:'alice'}})}));
vi.mock('../src/lib/firebase',()=>({firebaseConfigured:true}));
vi.mock('../src/lib/brainCloud',()=>({loadBrainAttempt:cloud.load,loadBrainPublication:cloud.publication,startBrainAttempt:cloud.start,finishBrainAttempt:cloud.finish,publishBrainScore:cloud.publish,withdrawBrainScore:cloud.withdraw,loadBrainScores:cloud.scores}));
const timestamp=(ms:number)=>({toMillis:()=>ms});
const attempt=()=>({day:brainDay(),status:'running',startedAt:timestamp(Date.now()-123400),finishedAt:null,answers:[]});
beforeEach(()=>{localStorage.clear();Object.values(cloud).forEach(f=>f.mockReset());cloud.load.mockResolvedValue(null);cloud.publication.mockResolvedValue(null);cloud.start.mockImplementation(async()=>attempt());cloud.scores.mockResolvedValue({scores:[],more:false});});afterEach(cleanup);
const mount=()=>render(<MemoryRouter><BrainPuzzles/></MemoryRouter>);
async function start(){mount();await waitFor(()=>expect(screen.getByRole('button',{name:'Începe cronometrul'})).toHaveProperty('disabled',false));fireEvent.click(screen.getByRole('button',{name:'Începe cronometrul'}));await screen.findByLabelText('Răspunsul puzzle-ului');}
async function solve(){for(const p of dailyBrainPuzzles(brainDay())){fireEvent.change(screen.getByLabelText('Răspunsul puzzle-ului'),{target:{value:String(p.answer)}});fireEvent.submit(screen.getByLabelText('Răspunsul puzzle-ului').closest('form')!);}}
it('ranked finish is private by default, uses server elapsed time, and can later publish and withdraw',async()=>{const a=attempt();cloud.start.mockResolvedValue(a);cloud.finish.mockResolvedValue({...a,status:'done',finishedAt:timestamp(a.startedAt.toMillis()+123400),answers:dailyBrainPuzzles(brainDay()).map(p=>p.answer)});cloud.publish.mockResolvedValue(undefined);cloud.withdraw.mockResolvedValue(undefined);await start();expect((screen.getByRole('checkbox') as HTMLInputElement).checked).toBe(false);await solve();await waitFor(()=>expect(screen.getByText('Timp confirmat de server.',{exact:false})).toBeTruthy());expect(cloud.finish).toHaveBeenCalledWith('alice',brainDay(),dailyBrainPuzzles(brainDay()).map(p=>p.answer),'',false);expect(screen.getByText('2:03.4',{selector:'.brain-result-time'})).toBeTruthy();fireEvent.click(screen.getByRole('checkbox'));fireEvent.change(screen.getByLabelText('Alias public'),{target:{value:'MinteCurioasă'}});fireEvent.click(screen.getByRole('button',{name:'Publică timpul confirmat'}));await waitFor(()=>expect(cloud.publish).toHaveBeenCalledWith('alice',brainDay(),'MinteCurioasă'));await screen.findByRole('button',{name:'Retrage timpul din clasament'});fireEvent.click(screen.getByRole('button',{name:'Retrage timpul din clasament'}));await waitFor(()=>expect(cloud.withdraw).toHaveBeenCalledWith('alice',brainDay()));});
it('offline finish keeps correct answers and retries without starting a new clock',async()=>{const a=attempt();cloud.start.mockResolvedValue(a);cloud.finish.mockRejectedValueOnce(new Error('offline')).mockResolvedValue({...a,status:'done',finishedAt:timestamp(Date.now()),answers:dailyBrainPuzzles(brainDay()).map(p=>p.answer)});await start();await solve();await screen.findByRole('button',{name:'Reîncearcă confirmarea'});await waitFor(()=>expect(screen.getByRole('button',{name:'Reîncearcă confirmarea'})).toHaveProperty('disabled',false));expect(JSON.parse(localStorage.getItem(`axioma:brain:alice:${brainDay()}`)!).answers).toHaveLength(3);fireEvent.click(screen.getByRole('button',{name:'Reîncearcă confirmarea'}));await waitFor(()=>expect(cloud.finish).toHaveBeenCalledTimes(2));expect(cloud.start).toHaveBeenCalledTimes(1);});
it('server attempts resume without requiring another start and board failures are retryable',async()=>{cloud.load.mockResolvedValue(attempt());cloud.scores.mockRejectedValueOnce(new Error('offline')).mockResolvedValue({scores:[{id:'a',alias:'Curios',startedMs:1000,finishedMs:2400}],more:false});mount();await screen.findByLabelText('Răspunsul puzzle-ului');expect(cloud.start).not.toHaveBeenCalled();fireEvent.click(screen.getByRole('button',{name:'Încarcă clasamentul'}));await screen.findByText('Clasamentul nu poate fi încărcat acum.',{exact:false});fireEvent.click(screen.getByRole('button',{name:'Încarcă clasamentul'}));await screen.findByText('Curios');});
it('a previously published result restores its consent and confirmed time on reload',async()=>{const a=attempt();cloud.load.mockResolvedValue({...a,status:'done',finishedAt:timestamp(a.startedAt.toMillis()+2100),answers:dailyBrainPuzzles(brainDay()).map(p=>p.answer)});cloud.publication.mockResolvedValue('Curios');mount();await screen.findByRole('button',{name:'Retrage timpul din clasament'});expect((screen.getByRole('checkbox') as HTMLInputElement).checked).toBe(true);expect((screen.getByLabelText('Alias public') as HTMLInputElement).value).toBe('Curios');expect(screen.getByText('0:02.1',{selector:'.brain-result-time'})).toBeTruthy();expect(cloud.start).not.toHaveBeenCalled();});
