import { expect,it,vi,afterEach } from 'vitest';
import { calendarPath,defaultPreferences,readPreferences,reminderDue,validateFeedback } from '../src/lib/engagement';
import { productReleases } from '../src/content/releases';
import { readFileSync } from 'node:fs';
afterEach(()=>vi.unstubAllGlobals());
it('validates feedback kinds and text boundaries',()=>{expect(validateFeedback({kind:'feature',title:'Idee nouă',message:'Aș dori mai multe exemple de geometrie.'})).toBe('');expect(validateFeedback({kind:'feature',title:'Mic',message:'Text'})).toContain('Titlul');expect(validateFeedback({kind:'feature',title:'Valid',message:'x'.repeat(2001)})).toContain('Mesajul');expect(validateFeedback({kind:'bad' as 'feature',title:'Valid',message:'x'.repeat(30)})).toContain('tipul');});
it('reminders require subscription, respect local days/time, studied dates and daily dismissal',()=>{const monday=new Date(2026,9,12,18,0);const p={...defaultPreferences,reminders:true};expect(reminderDue(defaultPreferences,[],monday)).toBe(false);expect(reminderDue(p,[],new Date(2026,9,12,17,59))).toBe(false);expect(reminderDue(p,[],monday)).toBe(true);expect(reminderDue(p,['2026-10-12'],monday)).toBe(false);expect(reminderDue({...p,reminderSeen:'2026-10-12'},[],monday)).toBe(false);expect(reminderDue({...p,days:'weekdays'},[],new Date(2026,9,11,20))).toBe(false);expect(reminderDue(p,[],new Date(2026,9,11,20))).toBe(true);});
it('malformed preferences recover safely and do not opt users in',()=>{vi.stubGlobal('localStorage',{getItem:()=>'{bad'});expect(readPreferences('key')).toEqual(defaultPreferences);vi.stubGlobal('localStorage',{getItem:()=>JSON.stringify({reminders:'yes',time:'9999',days:'anything'})});expect(readPreferences('key')).toEqual(defaultPreferences);});
it('all subscription URLs resolve to recurring valid calendar feeds with local time and alarms',()=>{for(const days of ['daily','weekdays'] as const)for(const time of ['0800','1600','1800','2000'] as const){const path=calendarPath({days,time});const text=readFileSync(`public${path}`,'utf8');expect(text).toContain('BEGIN:VCALENDAR\r\n');expect(text).toContain(`DTSTART:20260105T${time}00`);expect(text).toContain(days==='daily'?'RRULE:FREQ=DAILY':'RRULE:FREQ=WEEKLY;BYDAY=MO,TU,WE,TH,FR');expect(text).toContain('TRIGGER:PT0M');expect(text).toContain('END:VCALENDAR\r\n');expect(text.split('\r\n').every(line=>line.length<=75)).toBe(true);}});

it('deployment manifest, package and release feed identify the same release',()=>{const manifest=JSON.parse(readFileSync('public/release.json','utf8'));const pkg=JSON.parse(readFileSync('package.json','utf8'));expect(manifest.version).toBe(pkg.version);expect(manifest.version).toBe(productReleases[0].version);});
