// @vitest-environment jsdom
import { afterEach,it,expect,vi,beforeEach } from 'vitest';
import { cleanup,fireEvent,render,screen,waitFor } from '@testing-library/react';
import { MemoryRouter } from 'react-router-dom';
import { Feedback } from '../src/pages/Feedback';
const mocks=vi.hoisted(()=>({user:null as null|{uid:string},send:vi.fn(),load:vi.fn()}));
vi.mock('../src/hooks/useLearning',()=>({useLearning:()=>({user:mocks.user})}));
vi.mock('../src/lib/engagement',async importOriginal=>({...await importOriginal<typeof import('../src/lib/engagement')>(),sendFeedback:mocks.send,loadFeedback:mocks.load}));
beforeEach(()=>{localStorage.clear();mocks.user=null;mocks.send.mockReset();mocks.load.mockReset().mockResolvedValue([]);});afterEach(cleanup);
const fill=()=>{fireEvent.change(screen.getByLabelText('Titlu'),{target:{value:'O funcție utilă'}});fireEvent.change(screen.getByRole('textbox',{name:'Mesaj'}),{target:{value:'Aș dori mai multe exerciții de geometrie în spațiu.'}});};
it('guest drafts persist and no message is sent without authentication',()=>{const view=render(<MemoryRouter><Feedback/></MemoryRouter>);fill();fireEvent.submit(screen.getByRole('button',{name:'Trimite mesajul'}).closest('form')!);expect(mocks.send).not.toHaveBeenCalled();expect(screen.getByRole('status').textContent).toContain('Conectează-te');view.unmount();render(<MemoryRouter><Feedback/></MemoryRouter>);expect((screen.getByLabelText('Titlu') as HTMLInputElement).value).toBe('O funcție utilă');});
it('signed-in submission reaches the backend and clears only its own draft',async()=>{mocks.user={uid:'alice'};mocks.send.mockResolvedValue('id');localStorage.setItem('axioma:feedback-draft:guest',JSON.stringify({kind:'feature',title:'Ciornă vizitator',message:'Idei pentru alte exerciții de geometrie.'}));render(<MemoryRouter><Feedback/></MemoryRouter>);fireEvent.click(screen.getByRole('button',{name:'Preia ciorna de vizitator'}));fireEvent.submit(screen.getByRole('button',{name:'Trimite mesajul'}).closest('form')!);await waitFor(()=>expect(mocks.send).toHaveBeenCalledWith('alice',{kind:'feature',title:'Ciornă vizitator',message:'Idei pentru alte exerciții de geometrie.'}));await waitFor(()=>expect(screen.getByRole('status').textContent).toContain('Mulțumim'));expect(localStorage.getItem('axioma:feedback-draft:alice')).toBeNull();expect(localStorage.getItem('axioma:feedback-draft:guest')).not.toBeNull();});
it('network failures retain the draft and show a retryable error',async()=>{mocks.user={uid:'alice'};mocks.send.mockRejectedValue(new Error('Trimiterea nu a reușit.'));render(<MemoryRouter><Feedback/></MemoryRouter>);fill();fireEvent.submit(screen.getByRole('button',{name:'Trimite mesajul'}).closest('form')!);await waitFor(()=>expect(screen.getByRole('status').textContent).toContain('nu a reușit'));expect(localStorage.getItem('axioma:feedback-draft:alice')).toContain('O funcție utilă');expect(screen.getByRole('button',{name:'Trimite mesajul'})).toHaveProperty('disabled',false);});
