import { describe,it,expect } from 'vitest';
import katex from 'katex';
import { getRecap, middleSchoolTopics, recommendedRecap } from '../src/content/recaps';
import { courseLessons } from '../src/content/curriculum';
describe('optional recaps',()=>{
 it('offers four middle-school packs with original worked material and 48 distinct exercises',()=>{const ids:string[]=[];for(const grade of [5,6,7,8] as const){const pack=getRecap(String(grade),'2026')!;expect(pack.topics).toHaveLength(4);expect(pack.questions).toHaveLength(12);for(const t of middleSchoolTopics[grade]){expect(t.theory.length).toBeGreaterThanOrEqual(2);expect(t.example.steps).toHaveLength(3);expect(()=>katex.renderToString(t.formula,{throwOnError:true}),t.id).not.toThrow();for(const q of t.questions){ids.push(q.id);expect(q.options).toHaveLength(4);expect(new Set(q.options).size).toBe(4);expect(q.answer).toBeGreaterThanOrEqual(0);expect(q.answer).toBeLessThan(4);expect(q.explanation.length,q.id).toBeGreaterThan(10);}}}expect(ids).toHaveLength(48);expect(new Set(ids).size).toBe(48);});
 it('makes the combined recap sample every middle-school topic exactly once',()=>{const combined=getRecap('gimnaziu','2026')!;expect(combined.topics).toHaveLength(16);expect(combined.questions).toHaveLength(16);for(const topic of combined.topics)expect(combined.questions.some(q=>topic.questions.some(t=>t.id===q.id))).toBe(true);});
 it('offers an optional bridge before each high-school year',()=>{expect([9,10,11,12].map(g=>recommendedRecap(g as 9|10|11|12))).toEqual(['gimnaziu','9','10','11']);});
 it('keeps high-school recap concepts mapped to their selected curriculum and covers every grade',()=>{for(const version of ['legacy','2026'] as const)for(const grade of [9,10,11,12] as const){const pack=getRecap(String(grade),version)!;expect(pack.topics.map(t=>t.lessonId)).toEqual(courseLessons(grade,version).map(l=>l.id));expect(pack.questions).toHaveLength(12);expect(new Set(pack.questions.map(q=>q.id)).size).toBe(12);expect(pack.questions).toEqual(getRecap(String(grade),version)!.questions);}expect(getRecap('10','2026')!.topics.some(t=>t.lessonId==='polinoame')).toBe(true);expect(getRecap('10','legacy')!.topics.some(t=>t.lessonId==='polinoame')).toBe(false);});
 it('rejects invalid or malformed recap identifiers',()=>{for(const id of ['','4','13','9foo','09','Infinity','<script>'])expect(getRecap(id,'2026')).toBeUndefined();});
});
