import { useEffect, useMemo, useState } from 'react';
import { Activity, BarChart3, BookOpenCheck, CalendarDays, Gauge, ShieldCheck, Sparkles, Target, Trophy, UserRound, Users } from 'lucide-react';
import { FeedbackInbox } from '../components/FeedbackInbox';
import { useLearning } from '../hooks/useLearning';
import { aggregatePlatform, summarizeProgress } from '../lib/analytics';
import { isAdministrator, listAdminUsers, loadAdminProgress } from '../lib/community';
import type { AdminUser } from '../lib/community';
import { emptyProgress, passed } from '../lib/progress';
import type { Progress } from '../lib/progress';

const number=(value:number)=>value.toLocaleString('ro-RO');
const date=(value:string)=>Number.isFinite(Date.parse(value))?new Intl.DateTimeFormat('ro-RO',{dateStyle:'medium',timeStyle:'short'}).format(new Date(value)):'—';

export function Admin(){
 const {user}=useLearning();const [usersList,setUsers]=useState<AdminUser[]>([]);const [selected,setSelected]=useState<string|null>(null);const [detail,setDetail]=useState<Progress>(emptyProgress);const [search,setSearch]=useState('');const [state,setState]=useState<'loading'|'ready'|'error'>('loading');
 const allowed=isAdministrator(user);
 useEffect(()=>{if(!allowed)return;let active=true;setState('loading');listAdminUsers().then(items=>{if(!active)return;setUsers(items);setSelected(current=>current??items[0]?.uid??null);setState('ready');}).catch(()=>active&&setState('error'));return()=>{active=false;};},[allowed]);
 useEffect(()=>{if(!allowed||!selected){setDetail(emptyProgress());return;}let active=true;loadAdminProgress(selected).then(progress=>active&&setDetail(progress)).catch(()=>active&&setDetail(emptyProgress()));return()=>{active=false;};},[allowed,selected]);
 const platform=useMemo(()=>aggregatePlatform(usersList),[usersList]);const filtered=usersList.filter(item=>`${item.displayName} ${item.email}`.toLowerCase().includes(search.toLowerCase()));const activeUser=usersList.find(item=>item.uid===selected);const detailed=summarizeProgress(detail);const recent=Object.entries(detail.results).filter(([id])=>!id.startsWith('daily:stage-')).sort(([,a],[,b])=>b.completedAt.localeCompare(a.completedAt)).slice(0,8);
 if(!user)return <div className="empty-state"><ShieldCheck size={42}/><h1>Panoul de administrare</h1><p>Conectează-te cu un cont de administrator.</p></div>;
 if(!allowed)return <div className="empty-state"><ShieldCheck size={42}/><h1>Acces restricționat.</h1><p>Acest spațiu este disponibil numai administratorilor Axioma.</p></div>;
 const metrics=[['Utilizatori',platform.users,Users],['Activi azi',platform.activeToday,Activity],['Activi în 7 zile',platform.active7Days,CalendarDays],['Utilizatori noi · 30 zile',platform.new30Days,UserRound],['XP total',platform.totalXp,Sparkles],['XP mediu',platform.averageXp,Gauge],['Lecții stăpânite',platform.lessonsCompleted,BookOpenCheck],['Teste trecute',platform.testsPassed,Target],['Provocări zilnice',platform.dailyChallenges,Trophy],['Zile de studiu',platform.studyDays,CalendarDays],['Serie medie',platform.averageStreak,Activity],['Scor mediu',`${platform.averageScore}%`,BarChart3]] as const;
 return <div className="page-enter admin-page"><div className="page-heading"><div><p className="eyebrow">ADMINISTRARE PLATFORMĂ</p><h1>Statistici Axioma<span className="accent-dot">.</span></h1><p>Date agregate și progres detaliat pentru fiecare utilizator.</p></div><span className="pill green-pill"><ShieldCheck size={16}/>Administrator</span></div>
 {state==='error'?<p className="notice">Statisticile nu au putut fi încărcate.</p>:<><section className="admin-metrics" aria-label="Statistici generale">{metrics.map(([label,value,Icon])=><article className="admin-metric" key={label}><Icon size={18}/><span>{label}</span><strong>{typeof value==='number'?number(value):value}</strong></article>)}</section>
 <div className="admin-insights"><section><h2>Distribuție pe clase</h2>{[9,10,11,12].map(grade=><div className="distribution-row" key={grade}><span>Clasa {grade}</span><div><i style={{width:`${platform.users?(platform.gradeDistribution[String(grade)]??0)/platform.users*100:0}%`}}/></div><strong>{platform.gradeDistribution[String(grade)]??0}</strong></div>)}</section><section className="admin-highlight"><span className="eyebrow">SEMNALE DE ACTIVITATE</span><strong>{platform.active30Days}</strong><p>utilizatori activi în ultimele 30 de zile</p><small>Seria maximă curentă: {platform.bestStreak} zile · Scor mediu: {platform.averageScore}%</small></section></div>
 <div className="admin-layout"><section className="admin-users"><div className="admin-section-head"><div><h2>Utilizatori</h2><p>{filtered.length} din {usersList.length}</p></div><label><span className="sr-only">Caută utilizatori</span><input value={search} onChange={event=>setSearch(event.target.value)} placeholder="Caută după nume sau e-mail"/></label></div><div className="admin-user-list">{filtered.map(item=><button key={item.uid} className={item.uid===selected?'selected':''} onClick={()=>setSelected(item.uid)}><span className="admin-user-avatar">{item.displayName.slice(0,2).toUpperCase()}</span><span><strong>{item.displayName}</strong><small>{item.email}</small></span><span><strong>{number(item.stats.xp)} XP</strong><small>{item.stats.currentStreak} zile serie</small></span></button>)}{state==='loading'&&<p>Se încarcă utilizatorii…</p>}{state==='ready'&&!filtered.length&&<p>Niciun utilizator găsit.</p>}</div></section>
 <section className="admin-detail" aria-live="polite">{activeUser?<><div className="admin-profile-head"><span className="admin-user-avatar large">{activeUser.displayName.slice(0,2).toUpperCase()}</span><div><h2>{activeUser.displayName}</h2><p>{activeUser.email}</p></div></div><dl className="admin-detail-grid"><div><dt>XP</dt><dd>{number(detailed.xp)}</dd></div><div><dt>Rang</dt><dd>{detailed.rank}</dd></div><div><dt>Clasa</dt><dd>{activeUser.grade}</dd></div><div><dt>Programă</dt><dd>{activeUser.curriculum==='2026'?'2026':'Anterioară'}</dd></div><div><dt>Lecții</dt><dd>{detailed.lessonsCompleted}</dd></div><div><dt>Teste</dt><dd>{detailed.testsPassed}</dd></div><div><dt>Provocări</dt><dd>{detailed.dailyChallenges}</dd></div><div><dt>Scor mediu</dt><dd>{detailed.averageScore}%</dd></div><div><dt>Zile studiate</dt><dd>{detailed.studyDays}</dd></div><div><dt>Serie</dt><dd>{detailed.currentStreak}</dd></div></dl><div className="admin-dates"><p><strong>Înscris:</strong> {date(activeUser.createdAt)}</p><p><strong>Ultima activitate:</strong> {date(activeUser.lastSeenAt)}</p></div><h3>Activitate recentă</h3><div className="admin-activity-list">{recent.map(([id,result])=><div key={id}><span><strong>{id.replace(':',' · ')}</strong><small>{date(result.completedAt)}</small></span><b className={passed(result)?'passed':''}>{result.correct}/{result.total}</b></div>)}{!recent.length&&<p>Nu există încă activități finalizate.</p>}</div></>:<p>Selectează un utilizator pentru detalii.</p>}</section></div></>}
 <FeedbackInbox/></div>;
}