import { useEffect, useMemo, useState } from 'react';
import { Check, Clock3, Copy, Flame, LogIn, Swords, Trash2, Trophy, UserPlus, Users, X } from 'lucide-react';
import { useNavigate } from 'react-router-dom';
import { useLearning } from '../hooks/useLearning';
import { login } from '../lib/firebase';
import { acceptFriendship, createChallenge, declineFriendship, getProfiles, pairLearningStreak, removeFriendship, requestFriendship, respondToChallenge, subscribeChallengeEntries, subscribeChallenges, subscribeFriendships } from '../lib/community';
import type { ChallengeEntry, ChallengeMode, FriendChallenge, Friendship, PublicProfile } from '../lib/community';

export function Community(){
 const {user,progress,update}=useLearning();const navigate=useNavigate();const [friendships,setFriendships]=useState<Friendship[]>([]);const [challenges,setChallenges]=useState<FriendChallenge[]>([]);const [profiles,setProfiles]=useState<Record<string,PublicProfile>>({});const [entries,setEntries]=useState<Record<string,ChallengeEntry[]>>({});const [code,setCode]=useState('');const [message,setMessage]=useState('');const [busy,setBusy]=useState(false);
 useEffect(()=>{if(!user)return;const stopFriends=subscribeFriendships(user.uid,setFriendships,()=>setMessage('Prietenii nu pot fi încărcați.'));const stopChallenges=subscribeChallenges(user.uid,setChallenges,()=>setMessage('Provocările nu pot fi încărcate.'));return()=>{stopFriends();stopChallenges();};},[user]);
 useEffect(()=>{if(!user)return;const ids=friendships.flatMap(item=>item.members).filter(uid=>uid!==user.uid);getProfiles(ids).then(setProfiles).catch(()=>setMessage('Profilurile prietenilor nu pot fi încărcate.'));},[friendships,user]);
 useEffect(()=>subscribeChallengeEntries(challenges.map(item=>item.id),setEntries,()=>setMessage('Scorurile provocărilor nu pot fi încărcate.')),[challenges]);
 const run=async(action:()=>Promise<unknown>,success?:string)=>{setBusy(true);setMessage('');try{await action();if(success)setMessage(success);}catch(error){setMessage(error instanceof Error?error.message:'Acțiunea nu a reușit.');}finally{setBusy(false);}};
 if(!user)return <div className="page-enter community-page"><div className="page-heading"><div><p className="eyebrow">ÎNVĂȚAȚI ÎMPREUNĂ</p><h1>Prieteni și dueluri<span className="accent-dot">.</span></h1><p>Conectează-te pentru provocări, notificări și serii comune.</p></div></div><section className="community-signin"><Users size={44}/><h2>Un ritm bun se ține mai ușor împreună.</h2><p>Contul păstrează invitațiile și rezultatele private între participanți.</p><button className="button primary" onClick={()=>run(login)}><LogIn size={17}/>Continuă cu Google</button>{message&&<p role="status" className="notice">{message}</p>}</section></div>;
 const incoming=friendships.filter(item=>item.status==='pending'&&item.recipientId===user.uid);const outgoing=friendships.filter(item=>item.status==='pending'&&item.requestedBy===user.uid);const active=friendships.filter(item=>item.status==='active');const visibleChallenges=challenges.filter(item=>item.status!=='declined');
 const profileFor=(item:Friendship)=>profiles[item.members.find(uid=>uid!==user.uid)!];
 const challengeResult=(challenge:FriendChallenge)=>{const scores=entries[challenge.id]??[];const mine=scores.find(entry=>entry.uid===user.uid);const other=scores.find(entry=>entry.uid!==user.uid);if(!mine)return null;if(!other)return `Scorul tău: ${mine.correct}/${mine.total} · așteptăm adversarul`;const mineRate=mine.correct/mine.total,otherRate=other.correct/other.total;return mineRate===otherRate?`Egalitate · ${mine.correct}/${mine.total}`:mineRate>otherRate?`Ai câștigat · ${mine.correct}/${mine.total} vs ${other.correct}/${other.total}`:`Adversarul a câștigat · ${mine.correct}/${mine.total} vs ${other.correct}/${other.total}`;};
 const start=(challenge:FriendChallenge)=>{update(current=>({...current,grade:challenge.grade,curriculum:challenge.curriculum}));navigate(`/quiz/${challenge.mode}/${challenge.grade}?challenge=${challenge.id}`);};
 const sendChallenge=(profile:PublicProfile,mode:ChallengeMode)=>run(()=>createChallenge(user,profile,mode,progress.grade,progress.curriculum),`Provocarea a fost trimisă lui ${profile.displayName}.`);
 const friendCards=useMemo(()=>active.map(item=>({item,profile:profileFor(item)})).filter(entry=>entry.profile),[active,profiles]);
 return <div className="page-enter community-page"><div className="page-heading"><div><p className="eyebrow">ÎNVĂȚAȚI ÎMPREUNĂ</p><h1>Prieteni și dueluri<span className="accent-dot">.</span></h1><p>Serii comune, provocări și rezultate private între prieteni.</p></div><span className="pill green-pill"><Users size={16}/>{active.length} prieteni</span></div>
 {message&&<p role="status" className="notice">{message}</p>}
 <div className="community-onboarding"><section className="friend-code"><p className="eyebrow">CODUL TĂU DE PRIETEN</p><strong>{user.uid}</strong><p>Trimite codul doar unei persoane pe care o cunoști.</p><button onClick={()=>run(()=>navigator.clipboard.writeText(user.uid),'Cod copiat.')}><Copy size={16}/>Copiază</button></section><form className="friend-invite" onSubmit={event=>{event.preventDefault();run(()=>requestFriendship(user,code),'Invitația a fost trimisă.').then(()=>setCode(''));}}><UserPlus size={26}/><div><h2>Adaugă un prieten</h2><p>Introdu codul primit de la el.</p></div><label><span className="sr-only">Cod de prieten</span><input value={code} onChange={event=>setCode(event.target.value)} placeholder="Cod de prieten" required/></label><button className="button primary" disabled={busy}>Trimite invitația</button></form></div>
 {(incoming.length>0||outgoing.length>0)&&<section className="community-section"><div className="section-heading"><div><h2>Invitații</h2><p>Conexiunea devine activă numai după acceptare.</p></div></div><div className="invite-list">{incoming.map(item=>{const profile=profileFor(item);return <article key={item.id}><span className="friend-avatar">{profile?.displayName.slice(0,2).toUpperCase()??'?'}</span><div><strong>{profile?.displayName??'Utilizator Axioma'}</strong><small>Vrea să învățați împreună</small></div><button className="icon-action accept" aria-label="Acceptă invitația" onClick={()=>run(()=>acceptFriendship(item,user),'Acum sunteți prieteni.')}><Check size={18}/></button><button className="icon-action" aria-label="Refuză invitația" onClick={()=>run(()=>declineFriendship(item))}><X size={18}/></button></article>;})}{outgoing.map(item=>{const profile=profileFor(item);return <article key={item.id}><span className="friend-avatar">{profile?.displayName.slice(0,2).toUpperCase()??'?'}</span><div><strong>{profile?.displayName??'Utilizator Axioma'}</strong><small>Invitație trimisă</small></div><span className="pending-label"><Clock3 size={15}/>În așteptare</span></article>;})}</div></section>}
 <section className="community-section"><div className="section-heading"><div><h2>Prieteni activi</h2><p>Seria comună numără zilele consecutive în care ați studiat amândoi.</p></div></div>{friendCards.length?<div className="friend-grid">{friendCards.map(({item,profile})=><article className="friend-card" key={item.id}><div className="friend-card-head"><span className="friend-avatar">{profile.displayName.slice(0,2).toUpperCase()}</span><div><h3>{profile.displayName}</h3><p>{profile.rank} · {profile.xp.toLocaleString('ro-RO')} XP</p></div><button className="icon-action remove" aria-label={`Elimină prietenia cu ${profile.displayName}`} onClick={()=>run(()=>removeFriendship(item))}><Trash2 size={16}/></button></div><div className="pair-streak"><Flame size={20}/><span><small>SERIE ÎMPREUNĂ</small><strong>{pairLearningStreak(progress.dates,profile.recentStudyDates)} zile</strong></span></div><div className="friend-actions"><button onClick={()=>sendChallenge(profile,'daily')} disabled={busy}><Swords size={16}/>Provocarea zilei</button><button onClick={()=>sendChallenge(profile,'test')} disabled={busy}><Trophy size={16}/>Test</button></div></article>)}</div>:<div className="empty-panel"><Users size={30}/><p>Adaugă primul prieten pentru a porni o serie comună.</p></div>}</section>
 <section className="community-section"><div className="section-heading"><div><h2>Provocări</h2><p>Fiecare participant își păstrează propriul scor.</p></div></div>{visibleChallenges.length?<div className="duel-list">{visibleChallenges.map(challenge=>{const incomingChallenge=challenge.status==='pending'&&challenge.opponentId===user.uid;const result=challengeResult(challenge);const opponent=challenge.createdBy===user.uid?challenge.opponentName:challenge.creatorName;return <article key={challenge.id}><span className="duel-icon"><Swords size={20}/></span><div><h3>{challenge.mode==='daily'?'Provocarea zilei':'Test de antrenament'}</h3><p>Cu {opponent} · Clasa a {challenge.grade}-a</p>{result&&<strong className="duel-result">{result}</strong>}</div>{challenge.status==='pending'?(incomingChallenge?<div className="duel-actions"><button className="button primary" onClick={()=>run(()=>respondToChallenge(challenge,user,true))}>Acceptă</button><button className="button secondary" onClick={()=>run(()=>respondToChallenge(challenge,user,false))}>Refuză</button></div>:<span className="pending-label"><Clock3 size={15}/>În așteptare</span>):!entries[challenge.id]?.some(entry=>entry.uid===user.uid)?<button className="button dark" onClick={()=>start(challenge)}>Începe</button>:<span className="pill neutral-pill">{entries[challenge.id]?.length===2?'Finalizată':'Scor trimis'}</span>}</article>;})}</div>:<div className="empty-panel"><Swords size={30}/><p>Nicio provocare încă. Invită un prieten la primul duel.</p></div>}</section>
 </div>;
}