import { Link, useParams } from 'react-router-dom';
import { ArrowRight, BookOpen, ChevronRight, Compass, GraduationCap, Play, Sparkles } from 'lucide-react';
import { courseLessons, roman } from '../content/curriculum';
import { getRecap, middleSchoolSource, recapRoman, recommendedRecap, type RecapGrade } from '../content/recaps';
import { useLearning } from '../hooks/useLearning';
import { passed } from '../lib/progress';
import { GlossaryText } from '../components/Glossary';
import { MathFormula } from '../components/Math';
export function RecapInvitation(){
 const {progress}=useLearning();const pack=getRecap(recommendedRecap(progress.grade),progress.curriculum)!;
 return <section className="recap-invitation" aria-label="Recapitulare opțională"><div className="recap-invitation-icon"><Compass size={25}/></div><div><span className="eyebrow">O BAZĂ BUNĂ, UN START MAI UȘOR</span><h2>Înainte de clasa a {roman[progress.grade]}-a</h2><p>{progress.grade===9?'Vrei să reiei ideile din clasele V–VIII?':`Vrei să reiei ideile din clasa a ${roman[(progress.grade-1) as 9|10|11]}-a?`} Recapitularea este opțională, fără XP.</p></div><div className="recap-invitation-actions"><Link className="button secondary" to={`/recapitulare/${pack.id}`}>Începe recapitularea<ChevronRight size={16}/></Link><Link className="text-link" to="/recapitulare">Toate recapitulările</Link></div></section>;
}
export function StartCourse(){
 const {progress}=useLearning();const course=courseLessons(progress.grade,progress.curriculum);const next=course.find(l=>!passed(progress.results[`lesson:${l.id}`]))??course[0];const pack=getRecap(recommendedRecap(progress.grade),progress.curriculum)!;
 return <div className="page-enter start-course"><Link className="back-link" to="/materie">‹ Înapoi la parcurs</Link><div className="page-heading"><div><p className="eyebrow">ALEGE CUM ÎNCEPI</p><h1>Pregătit pentru clasa a {roman[progress.grade]}-a?</h1><p>Un mic pas înapoi poate face următorul pas mai ușor. Alegerea îți aparține.</p></div></div><div className="start-choices"><section className="paper-card recap-start-card"><Compass size={36}/><span className="pill green-pill">OPȚIONAL</span><h2>{pack.title}</h2><p>{pack.summary} Citește reperele și exersează cu explicații, în ritmul tău.</p><Link className="button dark" to={`/recapitulare/${pack.id}`}>Începe recapitularea<ArrowRight size={17}/></Link><small>Fără XP și fără schimbarea scorurilor tale.</small></section><section className="paper-card"><GraduationCap size={36}/><h2>Merg direct la materia nouă</h2><p>Poți începe imediat și poți reveni oricând la recapitulare.</p><Link className="button primary" to={`/lectie/${next.id}`}>Începe clasa a {roman[progress.grade]}-a<Play size={16}/></Link><small>Următoarea lecție: {next.title}</small></section></div><Link className="text-link" to="/recapitulare">Alege o altă recapitulare<ChevronRight size={16}/></Link></div>;
}
export function RecapHub(){
 const {progress}=useLearning();
 return <div className="page-enter recap-page"><div className="page-heading"><div><p className="eyebrow">IDEILE BUNE MERITĂ REÎNTÂLNITE</p><h1>Recapitulări<span className="accent-dot">.</span></h1><p>Alege ce vrei să reamintești. Fără cronometru, fără XP, fără grabă.</p></div><BookOpen size={30}/></div><RecapInvitation/><section className="recap-hub-section"><h2>Gimnaziu · Clasele V–VIII</h2><p>Repere de numere, algebră și geometrie pentru o bază solidă.</p><Link className="recap-combined" to="/recapitulare/gimnaziu"><div><span className="eyebrow">ÎNAINTE DE CLASA A IX-A</span><h3>Recapitulare V–VIII</h3><p>16 repere, câte unul pe rând. Leagă ideile înainte de liceu.</p></div><ArrowRight size={23}/></Link><div className="recap-grade-grid">{([5,6,7,8] as const).map(g=><RecapCard key={g} grade={g}/>)}</div></section><section className="recap-hub-section"><h2>Liceu · Clasele IX–XII</h2><p>Reiei conceptele din programa {progress.curriculum==='2026'?'nouă 2026':'anterioară'} selectată, fără să schimbi clasa parcursului tău.</p><div className="recap-grade-grid">{([9,10,11,12] as const).map(g=><RecapCard key={g} grade={g}/>)}</div></section><p className="recap-footnote">Aceste recapitulări sintetizează reperele de bază. Parcursul complet pentru gimnaziu rămâne în planurile viitoare.</p></div>;
}
function RecapCard({grade}:{grade:RecapGrade}){
 const {progress}=useLearning();const pack=getRecap(String(grade),progress.curriculum)!;
 return <Link className="recap-grade-card" to={`/recapitulare/${grade}`}><span>{recapRoman[grade]}</span><h3>Clasa a {recapRoman[grade]}-a</h3><p>{pack.topics.length} repere · {pack.questions.length} exerciții</p><span className="recap-card-action">Reia ideile<ChevronRight size={16}/></span></Link>;
}
export function RecapPage(){
 const {id}=useParams();const {progress}=useLearning();const pack=getRecap(id??'',progress.curriculum);
 if(!pack)return <div className="empty-state"><h1>Recapitularea nu a fost găsită.</h1><Link className="button primary" to="/recapitulare">Alege o recapitulare</Link></div>;
 return <div className="page-enter recap-page"><Link className="back-link" to="/recapitulare">‹ Toate recapitulările</Link><div className="page-heading"><div><p className="eyebrow">O PUNTE CĂTRE URMĂTOAREA IDEE</p><h1>{pack.title}</h1><p>{pack.summary}</p></div><span className="pill green-pill">{pack.topics.length} repere · opțional</span></div><section className="recap-practice-bar"><div><Sparkles size={21}/><p><strong>Exersează ce ai reamintit.</strong> {pack.questions.length} întrebări, cu explicații și reluare după reîncărcare.</p></div><Link className="button dark" to={`/quiz/recap/${pack.id}`}>Exersează recapitularea<Play size={16}/></Link></section><div className="recap-topics">{pack.topics.map((topic,i)=><details className="paper-card recap-topic" key={topic.id} open={i===0}><summary><span className="step-number">{i+1}</span><h2>{topic.title}</h2><ChevronRight size={19}/></summary><div className="recap-topic-body">{topic.theory.map((text,n)=><p key={n}><GlossaryText text={text}/></p>)}<MathFormula value={topic.formula}/><div className="recap-example"><h3>Un exemplu, pas cu pas</h3><p><GlossaryText text={topic.example.prompt}/></p><ol>{topic.example.steps.map((text,n)=><li key={n}><GlossaryText text={text}/></li>)}</ol></div>{topic.lessonId&&<Link className="text-link" to={`/lectie/${topic.lessonId}`}>Explorează lecția completă<ChevronRight size={16}/></Link>}</div></details>)}</div><section className="paper-card recap-finish"><h2>Gata pentru următorul pas?</h2><p>Poți exersa din nou sau poți continua clasa a {roman[progress.grade]}-a. Recapitularea nu este o condiție de acces.</p><div><Link className="button primary" to={`/quiz/recap/${pack.id}`}>Exersează recapitularea</Link><Link className="button secondary" to="/materie">Continuă parcursul</Link></div></section><p className="recap-footnote">Antrenament fără XP; sesiunea se păstrează în această filă de browser.</p><div className="source-links">{pack.grade&&pack.grade>=9?<Link to="/viitor#programa">Surse pentru programa liceală</Link>:<a href={middleSchoolSource.url} target="_blank" rel="noreferrer">{middleSchoolSource.title}</a>}</div></div>;
}
