import { lesson as l } from './helpers';
export const grade9 = [
l(9,'logica','Logică și mulțimi','Propoziții și raționamente','Învață să construiești o demonstrație, pornind de la afirmații precise.',
['O propoziție este un enunț care are o singură valoare de adevăr. Un predicat devine propoziție după ce precizăm variabila sau un cuantificator.', 'Conjuncția cere ca ambele propoziții să fie adevărate; disjuncția cere cel puțin una. Implicația este falsă numai când ipoteza este adevărată și concluzia falsă.', 'Pentru a nega „pentru orice x, P(x)”, este suficient să afirmi că există un x pentru care P(x) este falsă. Un contraexemplu infirmă o afirmație universală.'],
'\\neg(\\forall x, P(x))\\iff \\exists x,\\neg P(x)',
['Este adevărat că orice număr prim este impar?','Numărul 2 este prim: are exact doi divizori pozitivi.','Numărul 2 este par, deci este un contraexemplu.','Afirmația universală este falsă.'],
[['Dacă p este adevărată și q falsă, ce valoare are p ⇒ q?','Fals','Adevărat','Nu se poate decide','Depinde de p','O implicație cu ipoteză adevărată și concluzie falsă este falsă.'],['Negația lui „toți elevii au rezolvat” este:','Există un elev care nu a rezolvat','Niciun elev nu a rezolvat','Toți au greșit','Există un elev care a rezolvat','Negația lui „pentru orice” este „există ... nu”.'],['Dacă p este falsă și q adevărată, p ∨ q este:','Adevărat','Fals','Nedefinit','Egal cu p','Disjuncția este adevărată dacă măcar o propoziție este adevărată.']]),
l(9,'multimi','Logică și mulțimi','Mulțimi, intervale și numere reale','Reuniune, intersecție și distanțe pe axa numerelor.',
['Intersecția conține elementele comune; reuniunea conține toate elementele celor două mulțimi, fără repetări. Diferența A ∖ B păstrează elementele din A care nu sunt în B.', 'Intervalele deschise nu includ capetele. Modulul unui număr este distanța sa față de zero. Inegalitatea |x − a| < r descrie punctele aflate la o distanță mai mică decât r de a.'],
'|x-a|<r\\iff a-r<x<a+r\\quad(r>0)',
['Rezolvă |x − 2| < 3.','Distanța de la x la 2 trebuie să fie mai mică decât 3.','Obținem −3 < x − 2 < 3.','Adăugăm 2: x ∈ (−1, 5).'],
[['Pentru A = {1, 2, 3} și B = {2, 4}, A ∩ B este:','{2}','{1, 2, 3, 4}','{1, 3}','{4}','Singurul element comun este 2.'],['Cât este |−5|?','5','−5','0','10','Modulul este o distanță, deci |−5| = 5.'],['Soluția lui |x| ≤ 2 este:','[−2, 2]','(−2, 2)','[0, 2]','ℝ','Capetele sunt incluse datorită semnului ≤.']]),
l(9,'inductie','Logică și mulțimi','Inducția matematică','Demonstrează o afirmație pentru toate numerele naturale.',
['O demonstrație prin inducție are două etape obligatorii: verificarea cazului inițial și pasul de inducție.', 'Presupunem afirmația adevărată pentru un n arbitrar și o demonstrăm pentru n + 1. Verificarea a oricât de multe exemple nu înlocuiește pasul de inducție.'],
'1+2+\\cdots+n=\\frac{n(n+1)}{2}',
['Demonstrează formula sumei primelor n numere naturale.','Pentru n = 1: 1 = 1·2/2.','Presupunem Sₙ = n(n+1)/2.','Sₙ₊₁ = Sₙ + n + 1 = (n+1)(n+2)/2.'],
[['Care este primul pas al inducției?','Verificarea cazului inițial','Verificarea a 100 de exemple','Presupunerea concluziei','Calcularea unei limite','Fără cazul inițial nu putem porni lanțul implicațiilor.'],['1 + 2 + ... + 10 = ?','55','50','100','45','Aplicăm 10·11/2 = 55.'],['În pasul de inducție demonstrăm:','P(n) implică P(n+1)','P(1) implică P(0)','P(n) este falsă','Doar P(2)','Ipoteza pentru n este folosită pentru a obține afirmația pentru n+1.']]),
l(9,'progresii-aritmetice','Șiruri și progresii','Progresii aritmetice','Descoperă regula din spatele unui șir cu pas constant.',
['Un șir asociază fiecărui număr natural un termen. Poate fi definit printr-o formulă sau prin recurență. Monotonia descrie ordinea termenilor.', 'Într-o progresie aritmetică diferența dintre doi termeni consecutivi este constantă: rația r. Dacă r > 0, șirul este strict crescător; dacă r < 0, strict descrescător.'],
'a_n=a_1+(n-1)r,\\qquad S_n=\\frac{n(a_1+a_n)}{2}',
['În progresia 3, 7, 11, … află a₁₀ și S₁₀.','Rația este r = 7 − 3 = 4.','a₁₀ = 3 + 9·4 = 39.','S₁₀ = 10·(3+39)/2 = 210.'],
[['În șirul 2, 5, 8, … rația este:','3','2','5','8','Diferența a doi termeni consecutivi este 5−2 = 3.'],['Dacă a₁ = 4 și r = 2, cât este a₅?','12','10','14','8','a₅ = 4 + (5−1)·2 = 12.'],['Suma 1 + 3 + 5 + 7 + 9 este:','25','20','30','45','S₅ = 5·(1+9)/2 = 25.']]),
l(9,'progresii-geometrice','Șiruri și progresii','Progresii geometrice','Modelează creșterea prin multiplicare repetată.',
['Într-o progresie geometrică fiecare termen este obținut înmulțind termenul precedent cu aceeași rație q.', 'Formula sumei cu numitorul q − 1 se folosește numai pentru q ≠ 1. Pentru q = 1, toți termenii sunt egali, iar suma este n·b₁.'],
'b_n=b_1q^{n-1},\\qquad S_n=b_1\\frac{q^n-1}{q-1}\\;(q\\ne1)',
['O cultură are inițial 5 bacterii și se dublează la fiecare oră. Câte sunt după 4 ore?','Momentul inițial este termenul b₁ = 5.','După 4 ore au avut loc 4 dublări.','Numărul este 5·2⁴ = 80.'],
[['În progresia 3, 6, 12, … cât este q?','2','3','6','1/2','q = 6/3 = 2.'],['Pentru b₁ = 2 și q = 3, b₄ = ?','54','18','81','24','b₄ = 2·3³ = 54.'],['Suma 1 + 2 + 4 + 8 este:','15','16','14','12','S₄ = (2⁴−1)/(2−1) = 15.']]),
l(9,'functii','Funcții și ecuații','Funcții. Domeniu și proprietăți','Citește o funcție ca pe o relație între două mărimi.',
['O funcție asociază fiecărui element din domeniu exact o valoare din codomeniu. Imaginea este mulțimea valorilor efectiv obținute.', 'O funcție pară satisface f(−x)=f(x); una impară satisface f(−x)=−f(x), pe un domeniu simetric. Monotonia trebuie verificată pe intervale.', 'Compunerea f ∘ g se calculează din interior spre exterior și este definită doar unde g(x) aparține domeniului lui f.'],
'(f\\circ g)(x)=f(g(x))',
['Pentru f(x)=2x+1 și g(x)=x², determină f(g(3)).','Mai întâi g(3)=9.','Apoi f(9)=2·9+1=19.','Ordinea contează: g(f(3))=49.'],
[['Domeniul real al lui f(x)=1/(x−2) este:','ℝ ∖ {2}','ℝ','(2, +∞)','{2}','Numitorul nu poate fi zero, deci x ≠ 2.'],['Funcția f(x)=x² este:','Pară','Impară','Strict crescătoare pe ℝ','Constantă','f(−x)=(−x)²=x²=f(x).'],['Dacă f(x)=x+2 și g(x)=3x, f(g(2))=?','8','12','6','10','g(2)=6, apoi f(6)=8.']]),
l(9,'gradul-unu','Funcții și ecuații','Funcția de gradul I','Panta și intersecția cu axele, explicate geometric.',
['Graficul lui f(x)=ax+b este o dreaptă. Pentru a ≠ 0, a este panta; b este ordonata intersecției cu axa Oy.', 'Funcția este crescătoare dacă a > 0 și descrescătoare dacă a < 0. La împărțirea unei inecuații cu un număr negativ, sensul inegalității se schimbă.'],
'f(x)=ax+b,\\qquad x_0=-\\frac{b}{a}\\;(a\\ne0)',
['Rezolvă −2x+6 > 0.','Mutăm termenul liber: −2x > −6.','Împărțim prin −2 și inversăm sensul.','Soluția este x < 3.'],
[['Panta dreptei y=3x−2 este:','3','−2','2','−3','Coeficientul lui x este panta.'],['Zeroul funcției f(x)=2x−8 este:','4','−4','8','2','2x−8=0 implică x=4.'],['Funcția f(x)=−x+5 este:','Strict descrescătoare','Strict crescătoare','Constantă','Pară','Coeficientul lui x este negativ.']]),
l(9,'gradul-doi','Funcții și ecuații','Funcția de gradul al II-lea','Dă viață parabolei. Explorează vârful, rădăcinile și semnul.',
['Pentru a ≠ 0, graficul lui f(x)=ax²+bx+c este o parabolă. Dacă a > 0, ramurile sunt orientate în sus, iar vârful este un minim.', 'Discriminantul Δ=b²−4ac stabilește numărul rădăcinilor reale: două pentru Δ>0, una dublă pentru Δ=0, niciuna pentru Δ<0.', 'Între două rădăcini reale distincte, funcția are semn opus lui a; în exterior are semnul lui a.'],
'x_{1,2}=\\frac{-b\\pm\\sqrt{\\Delta}}{2a},\\qquad V\\left(-\\frac b{2a},-\\frac{\\Delta}{4a}\\right)',
['Studiază f(x)=x²−4x+3.','a=1, b=−4, c=3, deci Δ=16−12=4.','Rădăcinile sunt (4±2)/2, adică 1 și 3.','Vârful este V(2,−1). Funcția este negativă pe (1,3).'],
[['Discriminantul lui x²−5x+6 este:','1','49','−1','5','Δ=(−5)²−4·1·6=25−24=1.'],['Abscisa vârfului lui f(x)=x²−4x+3 este:','2','−2','4','1','xᵥ=−b/(2a)=4/2=2.'],['Ecuația x²+1=0 are în ℝ:','Nicio soluție','O soluție','Două soluții','Infinit de multe soluții','x²≥0, deci x²+1≥1; echivalent, Δ=−4<0.']], 'quadratic'),
l(9,'viete','Funcții și ecuații','Relațiile lui Viète și inecuații','Leagă rădăcinile de coeficienți, fără a rezolva ecuația.',
['Dacă x₁ și x₂ sunt rădăcinile lui ax²+bx+c=0, suma lor este −b/a și produsul c/a.', 'Pentru inecuații de gradul al doilea, determină mai întâi rădăcinile și semnul lui a. Include rădăcinile numai la ≤ sau ≥.'],
'x_1+x_2=-\\frac ba,\\qquad x_1x_2=\\frac ca',
['Rezolvă x²−5x+6 ≤ 0.','Căutăm două numere cu suma 5 și produsul 6: 2 și 3.','Coeficientul lui x² este pozitiv.','Expresia este ≤0 între rădăcini: [2,3].'],
[['Suma rădăcinilor lui x²−7x+10=0 este:','7','10','−7','−10','Prin Viète, suma este −(−7)/1=7.'],['Produsul rădăcinilor lui 2x²−3x−5=0 este:','−5/2','5/2','3/2','−3/2','Produsul este c/a=−5/2.'],['Soluția lui x²−4 < 0 este:','(−2, 2)','[−2, 2]','(2, +∞)','ℝ','Parabola este negativă strict între rădăcinile −2 și 2.']]),
l(9,'radicali','Funcții și ecuații','Radicali și ecuații iraționale','Condițiile de existență fac parte din rezolvare.',
['În ℝ, radicalul de ordin par cere un radicand nenegativ. Radicalul pătrat este întotdeauna nenegativ, deci √(x²)=|x|.', 'Ridicarea la pătrat poate introduce soluții false. Impune condițiile inițiale și verifică fiecare candidat în ecuația originală.'],
'\\sqrt{x^2}=|x|,\\qquad \\sqrt{u}=v\\iff u=v^2\\text{ și }v\\ge0',
['Rezolvă √(x+2)=x.','Condiția membrului drept: x≥0.','Ridicăm la pătrat: x+2=x², deci x∈{−1,2}.','Doar x=2 respectă condiția și verifică ecuația.'],
[['√((-3)²) = ?','3','−3','9','−9','√(x²)=|x|, deci rezultatul este 3.'],['Domeniul lui √(x−4) este:','[4, +∞)','(4, +∞)','ℝ','(−∞, 4]','Trebuie x−4≥0.'],['Soluția lui √(x+1)=2 este:','3','1','5','−3','x+1=4, deci x=3, care verifică ecuația.']]),
l(9,'trigonometrie','Trigonometrie și geometrie','Cercul trigonometric','Unghiuri, radiani și identitatea fundamentală.',
['Pe cercul unitate, punctul corespunzător unghiului x are coordonatele (cos x, sin x). Un tur complet are 2π radiani, adică 360°.', 'Sinusul și cosinusul au valori între −1 și 1. Tangenta este sin x/cos x și este definită numai când cos x ≠ 0.'],
'\\sin^2x+\\cos^2x=1,\\qquad 180^\\circ=\\pi\\text{ rad}',
['Află sin 30° și cos 60°.','30°=π/6, iar 60°=π/3.','Din triunghiul echilateral împărțit în două obținem sin 30°=1/2.','Unghiurile sunt complementare, deci cos 60°=sin 30°=1/2.'],
[['90° în radiani este:','π/2','π','2π','π/4','180° corespund lui π, deci 90° lui π/2.'],['sin²x + cos²x = ?','1','0','2','sin x','Este identitatea fundamentală.'],['sin(π/2) = ?','1','0','−1','1/2','La un sfert de tur, punctul de pe cerc este (0,1).']], 'trigonometry'),
l(9,'formule-trig','Trigonometrie și geometrie','Formule și ecuații trigonometrice','Transformă sume de unghiuri în expresii calculabile.',
['Formulele de adunare permit calcularea valorilor la unghiuri compuse. Pentru cosinus, semnul din formulă este opus celui din argument.', 'Soluțiile trigonometrice sunt periodice. Ecuația sin x=0 are soluțiile x=kπ, iar cos x=0 are x=π/2+kπ, k întreg.'],
'\\sin(a+b)=\\sin a\\cos b+\\cos a\\sin b,\\quad \\cos 2a=1-2\\sin^2a',
['Calculează sin 75°.','Scriem 75°=45°+30°.','sin 75°=sin45°cos30°+cos45°sin30°.','Rezultatul este (√6+√2)/4.'],
[['sin(2x) este egal cu:','2 sin x cos x','2 sin x','sin²x','cos²x−sin²x','Aplicăm formula sinusului unei sume cu a=b=x.'],['Soluțiile lui sin x=0 sunt:','x=kπ, k∈ℤ','x=π/2+kπ','x=π/4+kπ','Doar x=0','Sinusul este zero în punctele de pe axa Ox.'],['cos(π) = ?','−1','1','0','1/2','Punctul de pe cerc la π radiani este (−1,0).']], 'trigonometry'),
l(9,'triunghi','Trigonometrie și geometrie','Relații metrice în triunghi','Teorema sinusurilor, a cosinusului și calculul ariei.',
['Notăm cu a, b, c laturile opuse unghiurilor A, B, C. Teorema cosinusului generalizează teorema lui Pitagora.', 'Aria este jumătate din produsul a două laturi și sinusul unghiului dintre ele. Cu semiperimetrul s, formula lui Heron este √[s(s−a)(s−b)(s−c)].', 'Raza cercului circumscris satisface a=2R sin A. Raza cercului înscris este r=Arie/s.'],
'a^2=b^2+c^2-2bc\\cos A,\\qquad \\mathcal A=\\frac{bc\\sin A}{2}',
['Două laturi sunt 3 și 4, iar unghiul dintre ele este 90°. Află a treia latură și aria.','cos90°=0, deci a²=9+16=25.','A treia latură este 5.','Aria este 3·4·sin90°/2=6.'],
[['Aria unui triunghi cu laturile 6 și 4 și unghiul cuprins 30° este:','6','12','24','3','Aria=6·4·(1/2)/2=6.'],['Într-un triunghi dreptunghic cu catetele 5 și 12, ipotenuza este:','13','17','7','√17','√(25+144)=√169=13.'],['Dacă a=6 și sin A=1/2, raza R este:','6','3','12','1','a=2R sin A implică 6=R.']]),
l(9,'ceva-menelaus','Trigonometrie și geometrie','Bisectoare, mediane, Ceva și Menelaus','Demonstrează concurența și coliniaritatea prin rapoarte.',
['Bisectoarea interioară împarte latura opusă în raportul laturilor adiacente. Mediana împarte latura opusă în două segmente egale.', 'Pentru puncte D, E, F pe laturile BC, CA, AB, teorema lui Ceva caracterizează concurența cevianelor prin produsul rapoartelor egal cu 1.', 'Menelaus caracterizează coliniaritatea a trei puncte de pe dreptele laturilor prin produsul rapoartelor de lungimi egal cu 1, cu configurația potrivită (unul sau trei puncte exterioare). Relația lui Stewart: b²m+c²n=a(d²+mn), unde a=m+n, BD=m, DC=n, AD=d, AC=b, AB=c.'],
'\\frac{BD}{DC}\\frac{CE}{EA}\\frac{AF}{FB}=1,\\qquad m_a=\\frac12\\sqrt{2b^2+2c^2-a^2}',
['Bisectoarea AD într-un triunghi ABC are AB=6, AC=9 și BC=10. Află BD.','BD/DC=AB/AC=2/3.','Scriem BD=2t și DC=3t, deci 5t=10.','t=2 și BD=4.'],
[['Dacă AB=4, AC=8 și AD este bisectoare, BD/DC este:','1/2','2','1','4','Raportul este AB/AC=4/8=1/2.'],['Produsul rapoartelor din teorema lui Ceva este:','1','0','2','−2','Pentru cevienele concurente și puncte interioare, produsul este 1.'],['Mediana împarte latura opusă în:','Două segmente egale','Raportul laturilor alăturate','Trei segmente','Unghiuri egale','Aceasta este definiția medianei.']], undefined, ['2026']),
l(9,'vectori','Vectori în plan','Vectori și operații','Adună deplasări și recunoaște vectorii coliniari.',
['Un vector are direcție, sens și modul. În coordonate, adunarea și înmulțirea cu un scalar se fac componentă cu componentă.', 'Vectorul AB are coordonatele B−A. Doi vectori nenuli sunt coliniari dacă unul este multiplu scalar al celuilalt.'],
'\\overrightarrow{AB}=(x_B-x_A,y_B-y_A),\\qquad |\\vec u|=\\sqrt{u_x^2+u_y^2}',
['Pentru A(1,2) și B(4,6), află AB și lungimea sa.','Scădem coordonatele: AB=(3,4).','Lungimea este √(3²+4²).','Obținem |AB|=5.'],
[['Suma vectorilor (1,2) și (3,−1) este:','(4,1)','(3,−2)','(2,3)','(4,3)','Adunăm componentele corespunzătoare.'],['Lungimea vectorului (3,4) este:','5','7','25','1','√(9+16)=5.'],['Vectorii (2,4) și (1,2) sunt:','Coliniari','Perpendiculari','Egali','Nuli','Primul este de două ori al doilea.']], 'vectors', ['legacy']),
l(9,'produs-scalar','Vectori în plan','Produsul scalar și aplicații','Verifică perpendicularitatea și calculează unghiuri.',
['Produsul scalar al vectorilor u și v este suma produselor coordonatelor corespunzătoare. Geometric, este |u|·|v|·cos θ.', 'Doi vectori nenuli sunt perpendiculari exact când produsul lor scalar este zero. Relația vectorială a centrului de greutate conduce la media coordonatelor vârfurilor.'],
'\\vec u\\cdot\\vec v=u_xv_x+u_yv_y=|u||v|\\cos\\theta',
['Sunt perpendiculari u=(2,1) și v=(1,−2)?','Calculăm u·v=2·1+1·(−2).','Produsul este 0.','Ambii vectori sunt nenuli, deci sunt perpendiculari.'],
[['(1,2) · (3,4) = ?','11','10','7','14','1·3+2·4=11.'],['Dacă doi vectori nenuli au produsul scalar 0, unghiul este:','90°','0°','180°','45°','cos θ=0 pentru θ∈[0,π], deci θ=90°.'],['Centrul de greutate pentru (0,0), (6,0), (0,3) este:','(2,1)','(3,2)','(6,3)','(1,2)','Media coordonatelor este (6/3,3/3)=(2,1).']], 'vectors', ['legacy']),
];
