import { lesson as l } from './helpers';
export const grade10 = [
l(10,'puteri','Funcții și logaritmi','Puteri și funcția putere','Extinde regulile puterilor la exponenți raționali și reali.',
['Pentru baza pozitivă, puterile cu exponent real păstrează regulile înmulțirii și împărțirii. Exponentul negativ înseamnă inversul puterii.', 'Pentru exponent fracționar m/n, puterea unei baze pozitive este radicalul de ordin n din puterea m. La baze negative trebuie verificate separat existența și paritatea numitorului.'],
'a^{u+v}=a^ua^v,\\quad a^{-u}=\\frac1{a^u},\\quad a^{m/n}=\\sqrt[n]{a^m}\\;(a>0)',
['Calculează 16^(3/4).','Rădăcina de ordin 4 din 16 este 2.','Ridicăm rezultatul la puterea 3.','Obținem 2³=8.'],
[['27^(2/3) = ?','9','18','6','3','Rădăcina cubică din 27 este 3; 3²=9.'],['2^(−3) = ?','1/8','−8','−6','8','Exponentul negativ dă inversul: 1/2³=1/8.'],['Pentru a>0, a²·a³ = ?','a⁵','a⁶','2a⁵','a','La aceeași bază se adună exponenții.']]),
l(10,'exponentiala','Funcții și logaritmi','Funcția exponențială','Creșteri rapide, ecuații și inecuații exponențiale.',
['Funcția aˣ este definită pe ℝ pentru a>0, a≠1 și are valori pozitive. Este crescătoare pentru a>1 și descrescătoare pentru 0<a<1.', 'Pentru aceeași bază admisă, egalitatea puterilor implică egalitatea exponenților. În inecuații, sensul se inversează dacă baza este între 0 și 1.'],
'a^x=a^y\\iff x=y\\quad(a>0, a\\ne1)',
['Rezolvă (1/2)ˣ > 1/8.','Scriem 1/8=(1/2)³.','Baza 1/2 este subunitară, deci funcția este descrescătoare.','Rezultă x<3.'],
[['2ˣ=32 are soluția:','5','4','16','3','32=2⁵.'],['Funcția (1/3)ˣ este:','Strict descrescătoare','Strict crescătoare','Constantă','Negativă','Baza este în intervalul (0,1).'],['3^(x+1)=27 are soluția:','2','3','4','1','27=3³, deci x+1=3.']]),
l(10,'logaritmi','Funcții și logaritmi','Logaritmi și ecuații logaritmice','Logaritmul răspunde la întrebarea: la ce putere?',
['logₐx este exponentul la care trebuie ridicată baza a pentru a obține x. Condițiile sunt x>0, a>0, a≠1.', 'Logaritmul transformă produsele în sume și puterile în factori. Nu există o regulă care să transforme log(x+y) în log x+log y.'],
'\\log_a(xy)=\\log_a x+\\log_a y,\\qquad \\log_a x=\\frac{\\ln x}{\\ln a}',
['Rezolvă log₂(x−1)=3.','Condiție: x−1>0, deci x>1.','Din definiție, x−1=2³=8.','x=9 respectă domeniul.'],
[['log₂8 = ?','3','4','2','16','2³=8, deci log₂8=3.'],['Domeniul lui ln(x−3) este:','(3, +∞)','[3, +∞)','ℝ','(0, +∞)','Argumentul trebuie să fie strict pozitiv.'],['log₃x=2 implică:','x=9','x=6','x=8','x=1/9','Prin definiție, x=3²=9.']]),
l(10,'inversa','Funcții și logaritmi','Funcții injective și inverse','Inversează o corespondență și verifică bijectivitatea.',
['O funcție injectivă nu atribuie aceeași valoare la două argumente distincte. O funcție surjectivă atinge toate valorile din codomeniu.', 'O funcție este inversabilă exact când este bijectivă. Domeniul și codomeniul se schimbă între ele, iar graficele sunt simetrice față de y=x.'],
'f^{-1}(f(x))=x',
['Determină inversa lui f:ℝ→ℝ, f(x)=2x−3.','Notăm y=2x−3.','Izolăm x=(y+3)/2.','f⁻¹(x)=(x+3)/2.'],
[['Inversa lui f(x)=x+5 pe ℝ este:','x−5','x+5','5−x','1/(x+5)','Rezolvăm y=x+5 pentru x.'],['f:ℝ→ℝ, f(x)=x² este injectivă?','Nu','Da','Doar dacă x=0','Întotdeauna bijectivă','f(1)=f(−1), deși 1≠−1.'],['O funcție este inversabilă dacă este:','Bijectivă','Doar injectivă','Doar surjectivă','Pară','Sunt necesare simultan injectivitatea și surjectivitatea.']]),
l(10,'complexe','Numere complexe','Numere complexe. Forma algebrică','Descoperă numerele dincolo de axa reală.',
['Un număr complex are forma z=a+bi, cu a,b reale și i²=−1. Partea reală este a, iar partea imaginară este b.', 'Conjugatul este a−bi; produsul cu conjugatul este a²+b². Modulul |z|=√(a²+b²) reprezintă distanța față de origine în planul complex.'],
'z\\overline z=|z|^2=a^2+b^2',
['Calculează (2+i)(3−2i).','Desfacem parantezele: 6−4i+3i−2i².','Folosim i²=−1.','Rezultatul este 8−i.'],
[['i² = ?','−1','1','i','−i','Aceasta este relația care definește unitatea imaginară.'],['Modulul lui 3+4i este:','5','7','25','1','|3+4i|=√(9+16)=5.'],['Conjugatul lui 2−3i este:','2+3i','−2−3i','−2+3i','3−2i','Conjugarea schimbă semnul părții imaginare.']]),
l(10,'moivre','Numere complexe','Forma trigonometrică și formula lui Moivre','Înmulțirea devine o rotație și o schimbare de scară.',
['Orice complex nenul poate fi scris r(cos θ+i sin θ), cu r=|z|>0 și argumentul θ determinat modulo 2π.', 'La înmulțire, modulele se înmulțesc, iar argumentele se adună. Rădăcinile de ordin n sunt așezate uniform pe un cerc.'],
'[r(\\cos\\theta+i\\sin\\theta)]^n=r^n(\\cos n\\theta+i\\sin n\\theta)',
['Calculează (1+i)⁴.','1+i are modul √2 și argument π/4.','Puterea a patra are modul (√2)⁴=4 și argument π.','Rezultatul este −4.'],
[['i⁴ = ?','1','−1','i','−i','i⁴=(i²)²=(−1)²=1.'],['Argumentul lui 1+i în [0,2π) este:','π/4','π/2','π','0','Părțile reală și imaginară sunt egale și pozitive.'],['Câte rădăcini complexe distincte are z³=1?','3','1','2','0','Rădăcinile unității de ordin 3 sunt distincte și egal distanțate pe cerc.']]),
l(10,'combinatorica','Combinatorică și probabilități','Permutări, aranjamente, combinări','Alege formula potrivită: contează sau nu ordinea?',
['Permutările ordonează toate cele n elemente. Aranjamentele aleg și ordonează k elemente din n. Combinările aleg k elemente fără a ține cont de ordine.', 'Regula produsului numără alegeri succesive. Regula sumei numără alternative disjuncte. Nu aduna cazuri care se suprapun fără a corecta intersecția.'],
'P_n=n!,\\quad A_n^k=\\frac{n!}{(n-k)!},\\quad C_n^k=\\frac{n!}{k!(n-k)!}',
['Câte echipe de 3 elevi poți forma din 5?','Ordinea membrilor nu contează, deci folosim combinări.','C₅³=5!/(3!·2!).','Rezultatul este 10.'],
[['În câte moduri se pot ordona 4 cărți distincte?','24','16','12','4','Sunt 4!=24 permutări.'],['C₅² = ?','10','20','25','5','5·4/(2·1)=10.'],['Pentru alegerea unui președinte și a unui adjunct din 5 persoane folosim:','A₅²=20','C₅²=10','5!=120','5²=25','Rolurile sunt diferite și o persoană nu ocupă ambele roluri.']]),
l(10,'binom','Combinatorică și probabilități','Binomul lui Newton','Găsește un coeficient fără să dezvolți tot polinomul.',
['Coeficienții dezvoltării lui (a+b)ⁿ sunt combinările din linia n a triunghiului lui Pascal.', 'Termenul cu indice k are exponentul n−k la a și k la b. Relația lui Pascal este Cₙᵏ=Cₙ₋₁ᵏ+Cₙ₋₁ᵏ⁻¹.'],
'(a+b)^n=\\sum_{k=0}^n\\binom nk a^{n-k}b^k',
['Află coeficientul lui x² în (1+x)⁵.','Selectăm termenul cu k=2.','Coeficientul este C₅².','Rezultatul este 10.'],
[['Coeficientul lui x în (1+x)⁴ este:','4','6','1','8','Coeficientul este C₄¹=4.'],['Suma coeficienților lui (1+x)⁵ este:','32','25','10','5','Înlocuim x=1: (1+1)⁵=32.'],['C₆² este egal cu:','C₆⁴','C₆³','C₅²','C₇²','Combinările complementare au indici k și n−k.']]),
l(10,'probabilitati','Combinatorică și probabilități','Probabilitatea unui eveniment','Numără cazurile favorabile într-un spațiu bine definit.',
['Pentru rezultate elementare echiprobabile, probabilitatea este raportul cazuri favorabile/cazuri posibile. Probabilitatea unui eveniment este între 0 și 1.', 'La reuniune, scădem intersecția pentru a nu număra de două ori. Evenimentul contrar are probabilitatea 1−P(A).'],
'P(A\\cup B)=P(A)+P(B)-P(A\\cap B)',
['Care este probabilitatea de a obține un număr par la aruncarea unui zar corect?','Spațiul rezultatelor este {1,2,3,4,5,6}.','Cazurile favorabile sunt {2,4,6}.','Probabilitatea este 3/6=1/2.'],
[['Probabilitatea de a obține 6 pe un zar corect este:','1/6','1/2','1/3','6','Un caz favorabil din șase echiprobabile.'],['Dacă P(A)=0,3, atunci P(non A) este:','0,7','0,3','1,3','0','1−0,3=0,7.'],['Probabilitatea unui eveniment imposibil este:','0','1','1/2','−1','Evenimentul imposibil nu are cazuri favorabile.']]),
l(10,'statistica','Combinatorică și probabilități','Statistică și educație financiară','Interpretează datele și calculează dobânzi.',
['Media este suma valorilor împărțită la numărul lor. Mediana este valoarea centrală a datelor ordonate (media celor două valori centrale pentru un număr par de date). Modul este valoarea cu frecvența maximă.', 'Frecvența relativă este raportul dintre frecvența absolută și numărul total. Dobânda compusă aplică procentul la noul capital la fiecare perioadă.'],
'\\overline x=\\frac1n\\sum_{i=1}^n x_i,\\qquad C_n=C_0(1+r)^n',
['Un capital de 1000 lei crește cu 10% pe an, cu capitalizare anuală. Cât valorează după 2 ani?','După primul an: 1000·1,1=1100 lei.','După al doilea an: 1100·1,1.','Capitalul final este 1210 lei.'],
[['Media numerelor 2, 4, 9 este:','5','4','6','15','(2+4+9)/3=5.'],['Mediana datelor 1, 3, 4, 8, 20 este:','4','3','7,2','8','Datele sunt ordonate; valoarea din mijloc este 4.'],['20% din 150 lei este:','30 lei','20 lei','15 lei','50 lei','0,20·150=30.']]),
l(10,'dreapta','Geometrie analitică','Drepte în plan','De la două puncte la o ecuație și o distanță.',
['Pentru o dreaptă neverticală prin două puncte, panta este variația lui y împărțită la variația lui x. Ecuația generală ax+by+c=0 include și dreptele verticale.', 'Două drepte neverticale sunt paralele dacă au pante egale și perpendiculare dacă produsul pantelor este −1.'],
'd(M,\\Delta)=\\frac{|ax_M+by_M+c|}{\\sqrt{a^2+b^2}}',
['Scrie dreapta prin A(1,2) și B(3,6).','Panta este (6−2)/(3−1)=2.','Ecuația punct-pantă: y−2=2(x−1).','Rezultă y=2x.'],
[['Panta dreptei prin (0,1) și (2,5) este:','2','4','1/2','1','(5−1)/(2−0)=2.'],['O dreaptă perpendiculară pe y=2x are panta:','−1/2','2','1/2','−2','Produsul pantelor trebuie să fie −1.'],['Distanța de la (0,0) la 3x+4y−10=0 este:','2','10','5','1','|−10|/√(9+16)=10/5=2.']], 'vectors'),
];
