import { lesson as l } from './helpers';
export const grade12 = [
l(12,'legi','Structuri algebrice','Legi de compoziție','Verifică asociativitatea, comutativitatea și elementul neutru.',
['O lege de compoziție internă asociază oricărei perechi de elemente dintr-o mulțime un element din aceeași mulțime. Înainte de proprietăți verificăm închiderea.', 'Comutativitatea înseamnă a★b=b★a. Asociativitatea înseamnă (a★b)★c=a★(b★c). Elementul neutru e satisface a★e=e★a=a.'],
'a\\star b=a+b+1,\\qquad e=-1',
['Pentru x★y=x+y+1 pe ℝ, găsește neutrul și simetricul lui x.','Din x★e=x rezultă x+e+1=x, deci e=−1.','Simetricul y satisface x★y=e=−1.','Așadar y=−x−2.'],
[['Elementul neutru pentru x★y=x+y+2 pe ℝ este:','−2','0','2','1','x+e+2=x implică e=−2.'],['Înmulțirea pe ℝ are element neutru:','1','0','−1','2','x·1=1·x=x.'],['Scăderea pe ℝ este asociativă?','Nu','Da','Doar pentru pozitive','Este și comutativă','(3−2)−1=0, dar 3−(2−1)=2.']]),
l(12,'grupuri','Structuri algebrice','Grupuri și subgrupuri','Recunoaște structura comună unor operații diferite.',
['Un grup are o operație internă asociativă, un element neutru și un simetric pentru fiecare element. Dacă operația este și comutativă, grupul este abelian.', 'O submulțime nevidă H a unui grup este subgrup dacă pentru orice a,b∈H avem a★b⁻¹∈H. Numerele naturale cu adunarea nu formează un grup, deoarece lipsesc opușii.'],
'(\\mathbb Z,+)\\text{ este grup abelian},\\qquad (\\mathbb R^*,\\cdot)\\text{ este grup abelian}',
['Arată că 2ℤ este subgrup al lui (ℤ,+).','Este nevid: 0∈2ℤ.','Pentru 2a și 2b, diferența este 2(a−b).','Diferența este tot pară; criteriul de subgrup se aplică.'],
[['Care este grup pentru operația indicată?','(ℤ,+)','(ℕ,+)','(ℤ,·)','(ℝ,·)','Întregii au opuși; la înmulțire, 0 nu are invers.'],['Inversul lui 5 în (ℝ*,·) este:','1/5','−5','0','5','5·(1/5)=1, elementul neutru multiplicativ.'],['Un grup comutativ se numește:','Abelian','Ciclic obligatoriu','Inel','Corp','Abelian înseamnă că operația grupului este comutativă.']]),
l(12,'modulo','Structuri algebrice','Clase de resturi și morfisme','Calculează pe un ceas și compară structuri algebrice.',
['În ℤₙ, două numere reprezintă aceeași clasă dacă diferența lor este divizibilă cu n. Sumele și produsele se reduc modulo n.', 'Un morfism de grupuri păstrează operația. Un morfism bijectiv este izomorfism. Ordinul unui element este cel mai mic număr pozitiv de repetări care dă neutrul, dacă există.', 'Într-un grup finit, ordinul unui subgrup divide ordinul grupului (Lagrange). În grupul aditiv ℤₙ, ordinul clasei lui k este n/cmmdc(n,k).'],
'\\varphi(a\\star b)=\\varphi(a)\\circ\\varphi(b)',
['Află inversul multiplicativ al lui 3 modulo 7.','Căutăm x cu 3x≡1 (mod 7).','3·5=15, iar 15≡1 (mod 7).','Inversul este clasa lui 5.'],
[['5+4 modulo 7 este:','2','9','1','3','9=7+2, deci restul este 2.'],['Ordinul lui 2 în grupul aditiv ℤ₆ este:','3','2','6','1','2+2+2≡0 mod 6; trei este minimul.'],['Un morfism bijectiv de grupuri este:','Izomorfism','Polinom','Determinant','Subgrup','Aceasta este definiția izomorfismului.']]),
l(12,'inele','Structuri algebrice','Inele și corpuri','Două operații, legate prin distributivitate.',
['Un inel are adunare de grup abelian și înmulțire asociativă, distributivă față de adunare. În convenția cu unitate, există și neutru multiplicativ.', 'Un corp este un inel comutativ cu 1≠0 în care orice element nenul are invers multiplicativ. ℚ, ℝ și ℂ sunt corpuri, dar ℤ nu este.'],
'\\mathbb Z_p\\text{ este corp}\\iff p\\text{ este prim}',
['Este ℤ₆ un corp?','Clasele lui 2 și 3 sunt nenule.','Produsul lor este clasa lui 6, adică 0.','Există divizori ai lui zero, deci ℤ₆ nu este corp.'],
[['Care mulțime este corp cu operațiile uzuale?','ℚ','ℤ','ℕ','2ℤ','Orice rațional nenul are invers rațional.'],['ℤ₇ este:','Corp','Doar semigrup','Fără element neutru','Cu 2·3=0','7 este prim, deci ℤ₇ este corp.'],['În ℤ₆, 2·3 este:','0','1','2','3','6 are restul 0 la împărțirea cu 6.']], undefined, ['legacy']),
l(12,'polinoame','Polinoame','Polinoame. Împărțire și Bézout','Găsește restul și factorii fără calcule inutile.',
['Un polinom este o sumă finită de puteri nenegative ale variabilei, cu coeficienți. Gradul produsului a două polinoame nenule este suma gradelor.', 'Restul împărțirii lui P(X) la X−a este P(a). Așadar X−a divide P exact când a este rădăcină. Schema Horner organizează rapid împărțirea.'],
'P(X)=(X-a)Q(X)+P(a)',
['Află restul împărțirii lui P(X)=X³−2X+1 la X−2.','Teorema restului spune să calculăm P(2).','P(2)=8−4+1.','Restul este 5.'],
[['Restul lui X²+1 la împărțirea cu X−2 este:','5','3','1','0','P(2)=4+1=5.'],['Dacă P(3)=0, atunci P este divizibil cu:','X−3','X+3','X²+3','3X','Prin Bézout, 3 este rădăcină, deci X−3 este factor.'],['Gradul produsului unor polinoame de grade 2 și 3 este:','5','6','3','1','Gradele se adună.']]),
l(12,'ecuatii-polinomiale','Polinoame','Rădăcini și ecuații polinomiale','Folosește substituții și relațiile lui Viète.',
['Un polinom complex de grad n≥1 are n rădăcini numărate cu multiplicitate. Pentru coeficienți reali, rădăcinile complexe nereale apar în perechi conjugate.', 'La ecuații bipătrate, substituția t=x² reduce problema la gradul doi. Pentru soluții reale păstrăm t≥0. La ecuații reciproce putem folosi t=x+1/x, pentru x≠0.'],
'x^4-5x^2+4=(x^2-1)(x^2-4)',
['Rezolvă în ℝ ecuația x⁴−5x²+4=0.','Punem t=x²≥0. Obținem t²−5t+4=0.','t∈{1,4}.','Revenim la x: soluțiile sunt −2,−1,1,2.'],
[['Câte rădăcini are un polinom complex de grad 3, cu multiplicități?','3','Cel mult 2','1','Infinit de multe','Teorema fundamentală a algebrei dă exact gradul.'],['Dacă 2+i este rădăcină a unui polinom real, mai este rădăcină:','2−i','−2+i','−2−i','i','Rădăcinile nereale ale polinoamelor reale apar conjugate.'],['Soluțiile reale ale lui x⁴=16 sunt:','−2 și 2','Doar 2','−4 și 4','Patru soluții reale','x⁴=16 implică x²=4 în ℝ, deci x=±2.']]),
l(12,'primitive','Calcul integral','Primitive și integrale nedefinite','Parcurge drumul invers al derivării.',
['O primitivă F a lui f pe un interval satisface F′=f. Două primitive ale aceleiași funcții pe un interval diferă printr-o constantă.', 'Constanta C nu trebuie omisă la o integrală nedefinită. Formula puterii nu se aplică exponentului −1; pentru 1/x folosim ln|x| pe intervale care nu conțin 0.'],
'\\int x^n\\,dx=\\frac{x^{n+1}}{n+1}+C\\;(n\\ne-1),\\quad\\int\\frac{1}{x}\\,dx=\\ln|x|+C',
['Calculează ∫(3x²−2) dx.','Integrăm separat cei doi termeni.','O primitivă a lui 3x² este x³; a lui −2 este −2x.','Rezultatul: x³−2x+C. Verificăm prin derivare.'],
[['∫ 2x dx = ?','x²+C','2x²+C','2+C','x+C','Derivata lui x² este 2x.'],['∫ eˣ dx = ?','eˣ+C','xeˣ+C','eˣ/x+C','ln x+C','Exponențiala naturală este propria derivată.'],['∫ 1/x dx pe (0,∞) este:','ln x+C','x²/2+C','−1/x²+C','1+C','Derivata lui ln x este 1/x.']]),
l(12,'integrala','Calcul integral','Integrala definită și sumele Riemann','Transformă multe fâșii mici într-o arie exactă.',
['Integrala definită este limita sumelor Riemann, când diviziunea devine tot mai fină. Funcțiile continue pe un interval compact sunt integrabile.', 'Formula Leibniz–Newton calculează integrala din valorile unei primitive la capete. Integrala este cu semn: porțiunile de sub axa Ox contribuie negativ.'],
'\\int_a^b f(x)\\,dx=F(b)-F(a)',
['Calculează ∫₀² x² dx.','O primitivă este F(x)=x³/3.','Aplicăm formula: F(2)−F(0).','Rezultatul este 8/3.'],
[['∫₀¹ 2x dx = ?','1','2','0','1/2','[x²]₀¹=1−0=1.'],['∫ₐᵃ f(x) dx este:','0','1','f(a)','a','Intervalul are lungime zero.'],['Schimbarea ordinii capetelor unei integrale:','Schimbă semnul','Nu schimbă nimic','O anulează','O dublează','∫ᵦᵃf=−∫ₐᵦf.']], 'integral'),
l(12,'metode-integrare','Calcul integral','Integrare prin părți și substituție','Alege metoda după structura integrandului.',
['Integrarea prin părți inversează regula derivării unui produs. Alege u astfel încât derivarea să simplifice expresia.', 'La schimbarea de variabilă, transformă atât diferențiala, cât și limitele unei integrale definite. Pentru primitive revino la variabila inițială.'],
'\\int u\\,v\prime\\,dx=uv-\\int u\prime v\\,dx',
['Calculează ∫ x eˣ dx.','Alegem u=x și v′=eˣ, deci u′=1 și v=eˣ.','Prin părți: xeˣ−∫eˣ dx.','Rezultatul este eˣ(x−1)+C.'],
[['∫ 2x cos(x²) dx = ?','sin(x²)+C','cos(x²)+C','2 sin x+C','−sin(x²)+C','Substituția t=x² are dt=2x dx.'],['∫ x eˣ dx = ?','(x−1)eˣ+C','xeˣ+C','(x+1)eˣ+C','eˣ+C','Integrarea prin părți dă xeˣ−eˣ+C.'],['La substituția t=x² pentru x∈[1,2], noile capete sunt:','1 și 4','1 și 2','0 și 4','2 și 4','Aplicăm substituția la fiecare capăt.']]),
l(12,'arii-volume','Calcul integral','Arii și volume de rotație','Aplică integralele unor obiecte geometrice.',
['Aria dintre graficele f și g pe [a,b] este integrala lui |f−g|. Găsește punctele de intersecție și separă intervalele unde ordinea se schimbă.', 'La rotația în jurul axei Ox a regiunii dintre o funcție continuă nenegativă și axă, volumul este π∫f².'],
'\\mathcal A=\\int_a^b|f(x)-g(x)|\\,dx,\\qquad V=\\pi\\int_a^b f(x)^2\\,dx',
['Calculează aria dintre y=x și y=x² pe [0,1].','Pe acest interval, x≥x².','Aria este ∫₀¹(x−x²)dx.','[x²/2−x³/3]₀¹=1/2−1/3=1/6.'],
[['Aria de sub y=2 pe [0,3] este:','6','3','2','9','Este un dreptunghi: 2·3=6.'],['Volumul rotației lui y=1, x∈[0,2], în jurul Ox este:','2π','π','4π','2','V=π∫₀²1 dx=2π.'],['Aria dintre axa Ox și y=−1 pe [0,2] este:','2','−2','0','1','Aria folosește valoarea absolută a funcției.']], 'integral'),
l(12,'conice','Geometrie analitică','Cercul, elipsa, hiperbola și parabola','Recunoaște curbele din ecuațiile lor.',
['Cercul este mulțimea punctelor la distanță fixă de un centru. Elipsa are suma distanțelor față de două focare constantă; hiperbola are diferența absolută constantă.', 'Parabola este locul geometric al punctelor egal depărtate de un focar și de o dreaptă directoare. Intersecțiile cu o dreaptă se găsesc rezolvând un sistem.'],
'(x-a)^2+(y-b)^2=r^2,\\quad\\frac{x^2}{a^2}+\\frac{y^2}{b^2}=1',
['Găsește centrul și raza cercului x²+y²−4x+6y−12=0.','Completăm pătratele: (x−2)²−4+(y+3)²−9−12=0.','Obținem (x−2)²+(y+3)²=25.','Centrul este (2,−3), iar raza 5.'],
[['Raza cercului x²+y²=9 este:','3','9','81','1','r²=9 și r>0, deci r=3.'],['Ecuația x²/9+y²/4=1 reprezintă:','O elipsă','O hiperbolă','O dreaptă','O parabolă','Suma pătratelor normalizate descrie o elipsă.'],['Centrul cercului (x−1)²+(y+2)²=4 este:','(1,−2)','(−1,2)','(1,2)','(−1,−2)','Citind forma standard obținem a=1 și b=−2.']]),
];
