import { useId, useState } from 'react';
import { RotateCcw, SlidersHorizontal } from 'lucide-react';
import { getLab } from '../content/labs';
import { binomial, complexPolar, exponential, progression } from '../lib/labMath';
import { GlossaryText } from './Glossary';
import type { LabKind } from '../content/types';
const X=(x:number)=>240+x*32;const Y=(y:number)=>160-y*24;const complexY=(y:number)=>160-y*32;
function curve(fn:(x:number)=>number,start=-7,end=7){return Array.from({length:201},(_,i)=>{const x=start+(end-start)*i/200;return `${i?'L':'M'}${X(x).toFixed(2)},${Y(fn(x)).toFixed(2)}`;}).join(' ');}
export function Lab({kind='quadratic',compact=false,exampleId}:{kind?:LabKind;compact?:boolean;exampleId?:string}) {
 const definition=getLab(kind);const initial=definition.examples.find(e=>e.id===exampleId)??definition.examples[0];const [selected,setSelected]=useState(initial.id);const current=definition.examples.find(e=>e.id===selected)!;
 const [a,setA]=useState(initial.a);const [b,setB]=useState(initial.b);const [c,setC]=useState(initial.c);const [t,setT]=useState(initial.t);const [geometric,setGeometric]=useState(initial.geometric??false);const uid=useId().replaceAll(':','');
 const load=(id:string)=>{const e=definition.examples.find(item=>item.id===id)!;setSelected(id);setA(e.a);setB(e.b);setC(e.c);setT(e.t);setGeometric(e.geometric??false);};const reset=()=>load(selected);
 const f=(x:number)=>kind==='derivative'?x*x/3:kind==='integral'?x*x/4:kind==='exponential'?exponential(a,x):a*x*x+b*x+c;
 const path=curve(f);const theta=t*Math.PI/180;
 const slider=(name:string,value:number,set:(n:number)=>void,min:number,max:number,step=1)=><label className="slider-row"><span>{name}</span><input aria-label={name} type="range" min={min} max={max} step={step} value={value} onChange={e=>set(Number(e.target.value))}/><output>{value}</output></label>;
 const title=definition.title;const polar=complexPolar(a,t);const sequence=progression(a,b,kind==='sequences'?t:1,geometric);const k=Math.min(b,t);

 return <section className={`lab ${compact?'compact':''}`} aria-label={title}>
  <div className="lab-header"><span><SlidersHorizontal size={16}/>{compact?'EXPLOREAZĂ O IDEE':title}</span><button className="icon-button" onClick={reset} aria-label="Resetează graficul"><RotateCcw size={16}/></button></div>
  {!compact&&<label className="lab-example-picker">Exemple ghidate<select aria-label="Exemplu de laborator" value={selected} onChange={e=>load(e.target.value)}>{definition.examples.map(e=><option key={e.id} value={e.id}>{e.title}</option>)}</select></label>}
  <svg viewBox="0 0 480 320" role="img" aria-label={`${title}. ${kind==='quadratic'?`a=${a}, b=${b}, c=${c}`:`Parametru ${t}`}`}>
   <defs><pattern id={`grid-${uid}`} width="32" height={kind==='complex'?32:24} patternUnits="userSpaceOnUse"><path d={`M 32 0 L 0 0 0 ${kind==='complex'?32:24}`} fill="none" stroke="currentColor" strokeOpacity=".1" strokeWidth="1"/></pattern><clipPath id={`clip-${uid}`}><rect width="480" height="320"/></clipPath><linearGradient id={`fill-${uid}`} x1="0" y1="0" x2="0" y2="1"><stop offset="0%" stopColor="#b8ea69" stopOpacity=".45"/><stop offset="100%" stopColor="#b8ea69" stopOpacity=".06"/></linearGradient></defs>
   <rect width="480" height="320" fill={`url(#grid-${uid})`}/>{kind==='sequences'||kind==='probability'?<path d="M20 270H460" stroke="currentColor" strokeOpacity=".3"/>:<><path d="M0 160H480 M240 0V320" stroke="currentColor" strokeOpacity=".3"/><text x="463" y="150">x</text><text x="250" y="18">y</text><text x="249" y="178">0</text></>}
   <g clipPath={`url(#clip-${uid})`}>
   {kind==='complex'?<><path d={`M240 160L${X(a)} ${complexY(t)}L${X(a)} 160Z`} fill={`url(#fill-${uid})`} stroke="#c6f36a" strokeWidth="3"/><circle cx={X(a)} cy={complexY(t)} r="6" fill="#a798ed"/><text x="18" y="28">Re(z) → x · Im(z) → y</text></>:kind==='sequences'?<>{sequence.terms.map((value,i)=><g key={i}><path d={`M${45+i*48} 270V${270-value*8}`} stroke="#a798ed" strokeWidth="2"/><circle cx={45+i*48} cy={270-value*8} r="5" fill="#c6f36a"/><text x={41+i*48} y="290">{i+1}</text><text x={41+i*48} y={258-value*8}>{value}</text></g>)}<text x="18" y="28">Indicele n · Valoarea aₙ</text></>:kind==='probability'?<><text x="8" y="274">0</text><text x="8" y="44">1</text>{Array.from({length:t+1},(_,i)=><g key={i}><rect x={25+i*420/(t+1)} y={270-binomial(t,a,i)*230} width={320/(t+1)} height={binomial(t,a,i)*230} fill={i===k?'#c6f36a':'#a798ed'} rx="3"/><text x={25+i*420/(t+1)} y="290">{i}</text></g>)}<text x="18" y="28">Succese k · Probabilitatea P(X=k)</text></>:kind==='trigonometry'?<><circle cx="240" cy="160" r="115" stroke="currentColor" strokeOpacity=".4" fill="none"/><path d={`M240 160L${240+115*Math.cos(theta)} ${160-115*Math.sin(theta)}L${240+115*Math.cos(theta)} 160Z`} fill={`url(#fill-${uid})`} stroke="#c6f36a" strokeWidth="2"/><circle cx={240+115*Math.cos(theta)} cy={160-115*Math.sin(theta)} r="7" fill="#c6f36a"/><text x="20" y="30">θ = {t}°</text></>:
   kind==='vectors'?<><path d={`M240 160L${X(a)} ${Y(t)}`} stroke="#c6f36a" strokeWidth="4"/><path d={`M240 160L${X(b+2)} ${Y(c)}`} stroke="#a798ed" strokeWidth="4"/><path d={`M${X(a)} ${Y(t)}L${X(a+b+2)} ${Y(t+c)}L${X(b+2)} ${Y(c)}`} stroke="currentColor" strokeOpacity=".5" strokeDasharray="5 5" fill="none"/><path d={`M240 160L${X(a+b+2)} ${Y(t+c)}`} stroke="#f8ca74" strokeWidth="3"/><circle cx={X(a+b+2)} cy={Y(t+c)} r="5" fill="#f8ca74"/></>:
   <>{kind==='integral'&&<path d={`${curve(f,0,t)}L${X(t)} 160L240 160Z`} fill={`url(#fill-${uid})`}/>}<path className="curve-line" d={path} fill="none" stroke="#c6f36a" strokeWidth="3.5" strokeLinecap="round"/>{kind==='derivative'?<><path d={curve(x=>f(t)+(2*t/3)*(x-t))} stroke="#aa9aec" strokeWidth="2"/><circle cx={X(t)} cy={Y(f(t))} r="6" fill="#c6f36a"/></>:kind==='exponential'?<circle cx={X(t)} cy={Y(f(t))} r="6" fill="#a798ed"/>:kind==='quadratic'&&a!==0&&<circle cx={X(-b/(2*a))} cy={Y(f(-b/(2*a)))} r="6" fill="#c6f36a"/>}</>}
   </g>
  </svg>
  <div className="lab-caption" aria-live="polite"><GlossaryText text={kind==='complex'?`z = ${a} ${t<0?'−':'+'} ${Math.abs(t)}i · |z| = ${polar.modulus.toFixed(2)} · arg z = ${polar.argument===null?'nedefinit':`${polar.argument.toFixed(1)}°`}`:kind==='sequences'?`a${geometric?'ₙ = a₁·qⁿ⁻¹':'ₙ = a₁+(n−1)r'} · a${t} = ${sequence.last.toFixed(2)} · S${t} = ${sequence.sum.toFixed(2)}`:kind==='probability'?`P(X=${k}) = ${binomial(t,a,k).toFixed(4)} · E(X) = ${(t*a).toFixed(2)}`:kind==='exponential'?`f(x) = ${a}ˣ · f(${t}) = ${exponential(a,t).toFixed(3)}`:kind==='trigonometry'?`sin θ = ${Math.sin(theta).toFixed(2)} · cos θ = ${Math.cos(theta).toFixed(2)}`:kind==='derivative'?`f(x) = x²/3 · f′(${t}) = ${(2*t/3).toFixed(2)}`:kind==='integral'?`∫₀${t} x²/4 dx = ${(t**3/12).toFixed(3)}`:kind==='vectors'?`u = (${a}, ${t}) · v = (${b+2}, ${c}) · u + v = (${a+b+2}, ${t+c})`:`f(x) = ${a}x² ${b<0?'−':'+'} ${Math.abs(b)}x ${c<0?'−':'+'} ${Math.abs(c)}`}/></div>
  <div className="lab-controls">{kind==='complex'?<>{slider('Partea reală',a,setA,-5,5,.25)}{slider('Partea imaginară',t,setT,-5,5,.25)}</>:kind==='exponential'?<>{slider('Baza a',a,setA,.25,3,.25)}{slider('Punctul x',t,setT,-4,4,.25)}</>:kind==='sequences'?<><label className="lab-example-picker">Tip de progresie<select aria-label="Tip de progresie" value={geometric?'geometric':'arithmetic'} onChange={e=>setGeometric(e.target.value==='geometric')}><option value="arithmetic">Aritmetică</option><option value="geometric">Geometrică</option></select></label>{slider('Primul termen',a,setA,-3,3)}{slider('Rația',b,setB,-2,2,.5)}{slider('Număr de termeni',t,setT,1,8)}</>:kind==='probability'?<>{slider('Probabilitatea p',a,setA,0,1,.05)}{slider('Număr de încercări',t,n=>{setT(n);setB(v=>Math.min(v,n));},2,12)}{slider('Succese k',k,setB,0,t)}</>:kind==='trigonometry'?slider('Unghi θ',t,setT,0,360):kind==='derivative'?slider('Punctul x',t,setT,-5,5,.1):kind==='integral'?slider('Limita superioară',t,setT,0,5,.1):kind==='vectors'?<>{slider('uₓ',a,setA,-5,5)}{slider('uᵧ',t,setT,-5,5)}</>:<>{slider('Coeficient a',a,setA,-2,2,.25)}{!compact&&<>{slider('Coeficient b',b,setB,-4,4,.5)}{slider('Coeficient c',c,setC,-4,4,.5)}</>}</>}</div>
  {!compact&&<p className="lab-investigation"><GlossaryText text={current.investigation}/></p>}
  {!compact&&<p className="lab-note">{kind==='quadratic'?(a===0?'a = 0: funcția nu mai este de gradul al doilea.':`Vârful V(${(-b/(2*a)).toFixed(2)}, ${f(-b/(2*a)).toFixed(2)}). ${a>0?'Vârful este un minim.':'Vârful este un maxim.'}`):kind==='sequences'?'Punctele arată termenii, nu o funcție continuă. Termenii care depășesc fereastra grafică rămân incluși în sumă.':kind==='probability'?'Modelul presupune încercări independente cu aceeași probabilitate de succes. Suma probabilităților tuturor barelor este 1.':kind==='complex'?'Argumentul afișat este în intervalul [−180°,180°]. Pentru zero, nu există o direcție.':kind==='exponential'?(a===1?'Baza 1 produce o funcție constantă.':a>1?'Baza supraunitară produce creștere strictă.':'Baza subunitară produce descreștere strictă.'):kind==='integral'?'Modifică limita superioară și compară aria cu valoarea integralei.':kind==='vectors'?'Verde: u. Violet: v. Auriu: suma u + v, construită cu regula paralelogramului.':'Mișcă punctul și urmărește cum se schimbă relațiile dintre valori.'}</p>}
 </section>;
}
