import { useEffect } from 'react';
import { BrowserRouter, Link, NavLink, Route, Routes, useLocation } from 'react-router-dom';
import { BookOpen, LayoutDashboard, Trophy, Zap, FlaskConical, Rocket, ChevronDown, Flame, Sparkles, GraduationCap, Cloud, CloudOff, RotateCcw, ShieldCheck, UserRound, UsersRound } from 'lucide-react';
import { LearningProvider, useLearning } from './hooks/useLearning';
import { roman } from './content/curriculum';
import type { Grade, CurriculumVersion } from './content/types';
import { rankFor, streak, xp } from './lib/progress';
import { Dashboard, Curriculum, LessonPage, Laboratory } from './pages/Learning';
import { Challenges, QuizPage } from './pages/Practice';
import { Ranks, Roadmap, Account } from './pages/More';
import { Community } from './pages/Community';
import { Admin } from './pages/Admin';
import { NotificationCenter } from './components/Notifications';
import { isAdministrator } from './lib/community';
const baseNavigation=[{to:'/',label:'Privire de ansamblu',Icon:LayoutDashboard},{to:'/materie',label:'Parcursul meu',Icon:BookOpen},{to:'/laborator',label:'Laborator interactiv',Icon:FlaskConical},{to:'/provocari',label:'Provocări și teste',Icon:Zap},{to:'/prieteni',label:'Prieteni și dueluri',Icon:UsersRound},{to:'/ranguri',label:'Ranguri și progres',Icon:Trophy}];
function Shell(){
 const {progress,update,user,sync,retry}=useLearning();const location=useLocation();const points=xp(progress);const rank=rankFor(points);
 const navigation=isAdministrator(user)?[...baseNavigation,{to:'/admin',label:'Administrare',Icon:ShieldCheck}]:baseNavigation;
 useEffect(()=>{window.scrollTo(0,0);document.querySelector<HTMLElement>('main')?.focus();},[location.pathname]);
 return <div className="app-shell"><a className="skip-link" href="#main">Sari la conținut</a><aside className="sidebar"><Link className="brand" to="/" aria-label="Axioma · Acasă"><img src="/favicon.svg" alt=""/><span>axioma<span className="brand-dot">.</span></span></Link><div className="subject-pill"><span className="subject-icon">∑</span><div><strong>Matematică</strong><small>Liceu · Clasele IX–XII</small></div></div><p className="nav-label">SPAȚIUL TĂU DE ÎNVĂȚARE</p><nav aria-label="Navigare principală">{navigation.map(({to,label,Icon})=><NavLink key={to} to={to} end={to==='/'}><Icon size={20}/><span>{label}</span>{to==='/laborator'&&<span className="tiny-new">NOU</span>}</NavLink>)}</nav><div className="sidebar-bottom"><Link to="/viitor" className="future-card"><Rocket size={22}/><strong>Ideile nu se opresc aici.</strong><span>Descoperă ce urmează <span aria-hidden="true">↗</span></span></Link><Link to="/cont" className="profile-link"><div className="avatar">{user?.displayName?.[0]??<UserRound size={20}/>}</div><div><strong>{user?.displayName?.split(' ')[0]??'Explorator'}</strong><small>{user?'Cont conectat':'Înveți ca vizitator'}</small></div><ChevronDown size={16}/></Link></div></aside>
 <div className="workspace"><header className="topbar"><div className="breadcrumb"><GraduationCap size={18}/><span>Matematică</span><span className="slash">/</span><strong>Clasa a {roman[progress.grade]}-a</strong></div><div className="topbar-actions"><span className="streak-chip" title="Zile consecutive de studiu"><Flame size={18}/>{streak(progress.dates)}<span>zile</span></span><span className="xp-chip"><Sparkles size={17}/>{points} XP</span><NotificationCenter/><Link to="/cont" className="header-avatar" aria-label="Contul meu">{user?.displayName?.[0]??'A'}</Link></div></header>
 <main id="main" tabIndex={-1}><div className="course-controls"><div className="path-label"><span className="status-dot"/> MATEMATICĂ–INFORMATICĂ</div><div className="selects"><label><span className="sr-only">Clasa</span><select aria-label="Clasa" value={progress.grade} onChange={e=>update(p=>({...p,grade:Number(e.target.value) as Grade}))}>{([9,10,11,12] as Grade[]).map(g=><option key={g} value={g}>Clasa a {roman[g]}-a</option>)}</select></label><label><span className="sr-only">Programa</span><select aria-label="Programa" value={progress.curriculum} onChange={e=>update(p=>({...p,curriculum:e.target.value as CurriculumVersion}))}><option value="2026">Programa nouă · 2026</option><option value="legacy">Programa anterioară</option></select></label></div></div>
 {progress.curriculum==='2026'&&progress.grade>9&&<div className="notice">Parcurs pentru noua generație: clasa a {roman[progress.grade]}-a aplică programa nouă din {2026+progress.grade-9}–{2027+progress.grade-9}. Pentru elevii acestei clase în 2026–2027, alege „Programa anterioară”.</div>}
 <Routes><Route path="/" element={<Dashboard/>}/><Route path="/materie" element={<Curriculum/>}/><Route path="/lectie/:id" element={<LessonPage/>}/><Route path="/laborator" element={<Laboratory/>}/><Route path="/provocari" element={<Challenges/>}/><Route path="/quiz/:mode/:id" element={<QuizPage/>}/><Route path="/prieteni" element={<Community/>}/><Route path="/ranguri" element={<Ranks/>}/><Route path="/viitor" element={<Roadmap/>}/><Route path="/cont" element={<Account/>}/><Route path="/admin" element={<Admin/>}/><Route path="*" element={<div className="empty-state"><h1>Pagina nu a fost găsită.</h1><Link className="button primary" to="/">Înapoi la parcurs</Link></div>}/></Routes>
 <footer><span>axioma. <span className="footer-motto">Un pas mic. O idee mare.</span></span><div className="sync-indicator">{sync==='error'||sync==='storage-error'?<><CloudOff size={14}/><span>{sync==='error'?'Sincronizare indisponibilă · salvat local':'Stocare locală indisponibilă'}</span>{sync==='error'&&<button onClick={retry} aria-label="Reîncearcă sincronizarea"><RotateCcw size={14}/></button>}</>:<><Cloud size={14}/><span>{sync==='local'?'Progres salvat în acest browser':sync==='saving'?'Se sincronizează…':sync==='loading'?'Se încarcă progresul…':'Progres sincronizat'}</span></>}</div><Link to="/ranguri">{rank.name}</Link></footer>
 </main></div></div>;
}
export default function App(){return <BrowserRouter><LearningProvider><Shell/></LearningProvider></BrowserRouter>;}
